In [2]:
import numpy as np 
import pandas as pd

In [3]:
df = pd.read_csv('NYPD_arrest_data_2022-2023.csv')

In [ ]:
df.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
0,220756993,11/19/2020,155.0,RAPE 2,104.0,RAPE,PL 1303001,F,B,41,0.0,18-24,M,BLACK,1013232.0,236725.0,40.816392,-73.895296,POINT (-73.89529641399997 40.816391847000034)
1,221995093,12/18/2020,177.0,SEXUAL ABUSE,116.0,SEX CRIMES,PL 1306503,F,K,84,0.0,45-64,M,WHITE,989013.0,192652.0,40.695469,-73.982825,POINT (-73.98282507899995 40.69546894100006)
2,221558560,12/09/2020,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,S,120,0.0,<18,M,BLACK,962748.0,174174.0,40.644726,-74.077483,POINT (-74.07748315899995 40.64472613100002)
3,217890363,09/15/2020,NaN,NaN,NaN,NaN,PL 2650022,M,B,44,0.0,25-44,M,BLACK,1009412.0,245306.0,40.839956,-73.909065,POINT (-73.90906496999997 40.83995593800007)
4,219517698,10/21/2020,153.0,RAPE 3,104.0,RAPE,PL 1302502,F,Q,112,0.0,25-44,M,WHITE HISPANIC,1025420.0,202485.0,40.722364,-73.851474,POINT (-73.85147389399998 40.72236368700004)

### Column Desc Decide later if this is worth keeping

Arrest Key

PD CD

KY CD

Law Code

Law Cat

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5725522 entries, 0 to 5725521
Data columns (total 19 columns):
 #   Column             Dtype
---  ------             -----
 0   ARREST_KEY         int64
 1   ARREST_DATE        object
 2   PD_CD              float64
 3   PD_DESC            object
 4   KY_CD              float64
 5   OFNS_DESC          object
 6   LAW_CODE           object
 7   LAW_CAT_CD         object
 8   ARREST_BORO        object
 9   ARREST_PRECINCT    int64
 10  JURISDICTION_CODE  float64
 11  AGE_GROUP          object
 12  PERP_SEX           object
 13  PERP_RACE          object
 14  X_COORD_CD         float64
 15  Y_COORD_CD         float64
 16  Latitude           float64
 17  Longitude          float64
 18  Lon_Lat            object
dtypes: float64(7), int64(2), object(10)
memory usage: 830.0+ MB

### Checking for Missing/Duplicate Values

In [ ]:
df.isna().sum()

ARREST_KEY               0
ARREST_DATE              0
PD_CD                  876
PD_DESC               9169
KY_CD                 9756
OFNS_DESC             9169
LAW_CODE               196
LAW_CAT_CD           23600
ARREST_BORO              8
ARREST_PRECINCT          0
JURISDICTION_CODE       10
AGE_GROUP               17
PERP_SEX                 0
PERP_RACE                0
X_COORD_CD               1
Y_COORD_CD               1
Latitude                 1
Longitude                1
Lon_Lat                  1
dtype: int64

In [ ]:
missing_percentage = (df['PD_CD'].isnull().sum() / len(df['PD_CD'])) * 100
print("Percentage of missing values in 'PD_CD' column:", missing_percentage)

Percentage of missing values in 'PD_CD' column: 0.015299915012115925

In [ ]:
missing_percentage = (df['KY_CD'].isnull().sum() / len(df['KY_CD'])) * 100
print("Percentage of missing values in 'KY_CD' column:", missing_percentage)

Percentage of missing values in 'KY_CD' column: 0.17039494390205817

In [ ]:
missing_percentage = (df['LAW_CAT_CD'].isnull().sum() / len(df['LAW_CAT_CD'])) * 100
print("Percentage of missing values in 'LAW_CAT' column:", missing_percentage)

Percentage of missing values in 'LAW_CAT' column: 0.41218949119399073

In [ ]:
misisng_KY_CD_rows = df[df['KY_CD'].isna()]
misisng_KY_CD_rows.head(12)

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
3,217890363,09/15/2020,NaN,NaN,NaN,NaN,PL 2650022,M,B,44,0.0,25-44,M,BLACK,1009412.0,245306.0,40.839956,-73.909065,POINT (-73.90906496999997 40.83995593800007)
6,174564403,02/08/2018,440.0,NaN,NaN,NaN,PL 1553502,F,M,18,0.0,25-44,M,BLACK,988211.0,218129.0,40.765397,-73.985702,POINT (-73.98570226399994 40.765397475000036)
12,212465831,04/28/2020,777.0,NaN,NaN,NaN,PL 1950200,F,K,75,2.0,45-64,M,BLACK HISPANIC,1016409.0,178125.0,40.655538,-73.884099,POINT (-73.88409879299998 40.65553848200005)
22,193203736,02/05/2019,777.0,NaN,NaN,NaN,PL 1950200,F,M,1,0.0,18-24,F,WHITE,982351.0,201758.0,40.720464,-74.006852,POINT (-74.00685220399998 40.720463840000036)
23,195191904,03/26/2019,440.0,NaN,NaN,NaN,PL 1553502,F,M,10,0.0,18-24,M,ASIAN / PACIFIC ISLANDER,983821.0,213359.0,40.752306,-74.001550,POINT (-74.00154983299996 40.75230591800005)
34,172102368,11/29/2017,475.0,NaN,NaN,NaN,PL 1651600,M,Q,103,1.0,25-44,M,BLACK,1039726.0,195270.0,40.702482,-73.799922,POINT (-73.799922252 40.702482133000046)
39,195483860,04/02/2019,440.0,NaN,NaN,NaN,PL 1553502,F,M,18,0.0,18-24,M,WHITE,991531.0,217373.0,40.763320,-73.973718,POINT (-73.97371790399995 40.763320339000074)
43,196887878,05/07/2019,440.0,NaN,NaN,NaN,PL 1553502,F,M,5,0.0,45-64,F,BLACK,983903.0,200257.0,40.716344,-74.001253,POINT (-74.00125319299997 40.71634415200003)
65,16884071,06/25/2006,NaN,NaN,NaN,NaN,NaN,NaN,K,66,0.0,25-44,M,WHITE HISPANIC,988073.0,173324.0,40.642418,-73.986226,POINT (-73.98622587199996 40.64241834200004)
68,200422025,07/30/2019,440.0,NaN,NaN,NaN,PL 1553502,F,B,44,0.0,45-64,M,WHITE HISPANIC,1006195.0,240321.0,40.826282,-73.920708,POINT (-73.92070763799995 40.826282132000074)
72,202955908,09/27/2019,440.0,NaN,NaN,NaN,PL 1553502,F,B,44,0.0,25-44,M,WHITE HISPANIC,1006537.0,244511.0,40.837782,-73.919458,POINT (-73.91945797099999 40.837781618000065)
73,200884771,08/09/2019,440.0,NaN,NaN,NaN,PL 1553502,F,Q,115,0.0,25-44,M,BLACK,1019657.0,213726.0,40.753242,-73.872206,POINT (-73.87220567099996 40.75324236500006)

In [ ]:
total_rows = len(df)
total_missing_count = df.isnull().sum()

for column, missing_count in total_missing_count.items():
    if missing_count > 0:
        missing_percentage = (missing_count / total_rows) * 100
        print(f"Percentage of missing values in '{column}' column: {missing_percentage:.2f}%")
        
total_missing_percentage = (total_missing_count.sum().sum() / (total_rows * len(df.columns))) * 100
print(f"Total percentage of missing values: {total_missing_percentage:.2f}%")

Percentage of missing values in 'PD_CD' column: 0.02%
Percentage of missing values in 'PD_DESC' column: 0.16%
Percentage of missing values in 'KY_CD' column: 0.17%
Percentage of missing values in 'OFNS_DESC' column: 0.16%
Percentage of missing values in 'LAW_CODE' column: 0.00%
Percentage of missing values in 'LAW_CAT_CD' column: 0.41%
Percentage of missing values in 'ARREST_BORO' column: 0.00%
Percentage of missing values in 'JURISDICTION_CODE' column: 0.00%
Percentage of missing values in 'AGE_GROUP' column: 0.00%
Percentage of missing values in 'X_COORD_CD' column: 0.00%
Percentage of missing values in 'Y_COORD_CD' column: 0.00%
Percentage of missing values in 'Latitude' column: 0.00%
Percentage of missing values in 'Longitude' column: 0.00%
Percentage of missing values in 'Lon_Lat' column: 0.00%
Total percentage of missing values: 0.05%

# Dropping all null values as they only make up .92% of entire dataset CARLOS FIX THE TOTAL COUNT OF NUMBER ABOVE

In [ ]:
df.dropna(inplace=True)

### Appropriating Data Types

In [ ]:
df['ARREST_DATE'] = pd.to_datetime(df['ARREST_DATE'])

In [ ]:
df['ARREST_DATE'].head()

0   2020-11-19
1   2020-12-18
2   2020-12-09
4   2020-10-21
5   2020-09-21
Name: ARREST_DATE, dtype: datetime64[ns]

In [ ]:
filtered_df = df[(df['ARREST_DATE'].dt.year >= 2021) & (df['ARREST_DATE'].dt.year <= 2023)]

In [ ]:
df_date_min = filtered_df['ARREST_DATE'].dt.year.min()
df_date_max= filtered_df['ARREST_DATE'].dt.year.max()
print(f'The min month recorded in datatset is {df_date_min} and the max is {df_date_max}')

The min month recorded in datatset is 2021 and the max is 2023

In [ ]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 566724 entries, 97 to 1923098
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ARREST_KEY         566724 non-null  int64
 1   ARREST_DATE        566724 non-null  datetime64[ns]
 2   PD_CD              566724 non-null  float64
 3   PD_DESC            566724 non-null  object
 4   KY_CD              566724 non-null  float64
 5   OFNS_DESC          566724 non-null  object
 6   LAW_CODE           566724 non-null  object
 7   LAW_CAT_CD         566724 non-null  object
 8   ARREST_BORO        566724 non-null  object
 9   ARREST_PRECINCT    566724 non-null  int64
 10  JURISDICTION_CODE  566724 non-null  float64
 11  AGE_GROUP          566724 non-null  object
 12  PERP_SEX           566724 non-null  object
 13  PERP_RACE          566724 non-null  object
 14  X_COORD_CD         566724 non-null  float64
 15  Y_COORD_CD         566724 non-null  float64
 16  Latitude           566724 non-null  float64
 17  Longitude          566724 non-null  float64
 18  Lon_Lat            566724 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(2), object(9)
memory usage: 86.5+ MB

In [ ]:
filtered_df['LAW_CAT_CD'].describe()

count     566724
unique         5
top            M
freq      308489
Name: LAW_CAT_CD, dtype: object

In [ ]:
filtered_df['LAW_CAT_CD'].unique()

array(['F', 'M', 'V', 'I', '9'], dtype=object)

In [ ]:
print(df['OFNS_DESC'].unique())
print(f'Total unique elements in offensive description is: {len(df["OFNS_DESC"].unique())}')

['RAPE' 'SEX CRIMES' 'ARSON' 'JOSTLING' 'ESCAPE 3'
 'ASSAULT 3 & RELATED OFFENSES' 'FORCIBLE TOUCHING' 'CRIMINAL TRESPASS'
 'CRIMINAL MISCHIEF & RELATED OFFENSES' 'DANGEROUS DRUGS' 'FELONY ASSAULT'
 'OTHER TRAFFIC INFRACTION' 'OTHER STATE LAWS (NON PENAL LAW)'
 'PETIT LARCENY' 'OTHER STATE LAWS'
 'OFF. AGNST PUB ORD SENSBLTY & RGHTS TO PRIV'
 'POSSESSION OF STOLEN PROPERTY 5' 'INTOXICATED & IMPAIRED DRIVING'
 'PROSTITUTION & RELATED OFFENSES'
 'OFFENSES AGAINST PUBLIC ADMINISTRATION' 'BURGLARY' 'DANGEROUS WEAPONS'
 'OTHER OFFENSES RELATED TO THEFT' "BURGLAR'S TOOLS" 'GRAND LARCENY'
 'ROBBERY' 'INTOXICATED/IMPAIRED DRIVING' 'MISCELLANEOUS PENAL LAW'
 'OFFENSES INVOLVING FRAUD' 'THEFT-FRAUD' 'VEHICLE AND TRAFFIC LAWS'
 'ANTICIPATORY OFFENSES' 'MOVING INFRACTIONS'
 'POSSESSION OF STOLEN PROPERTY' 'DISORDERLY CONDUCT'
 'GRAND LARCENY OF MOTOR VEHICLE' 'FORGERY' 'FRAUDS' 'HARRASSMENT 2'
 'MURDER & NON-NEGL. MANSLAUGHTER' 'OFFENSES RELATED TO CHILDREN'
 'HOMICIDE-NEGLIGENT-VEHICLE' 'UNAUTHORIZED USE OF A VEHICLE 3 (UUV)'
 'ALCOHOLIC BEVERAGE CONTROL LAW' 'OFFENSES AGAINST THE PERSON' 'GAMBLING'
 'UNLAWFUL POSS. WEAP. ON SCHOOL GROUNDS' 'FRAUDULENT ACCOSTING'
 'HARASSMENT' 'KIDNAPPING & RELATED OFFENSES'
 'OFFENSES AGAINST PUBLIC SAFETY' 'ADMINISTRATIVE CODE' 'LOITERING'
 'LOITERING FOR DRUG PURPOSES' 'CHILD ABANDONMENT/NON SUPPORT 1'
 'LOITERING/GAMBLING (CARDS, DICE, ETC)' 'HOMICIDE-NEGLIGENT,UNCLASSIFIED'
 'DISRUPTION OF A RELIGIOUS SERVICE' 'PARKING OFFENSES' 'FORTUNE TELLING'
 'OFFENSES AGAINST MARRIAGE UNCLASSIFIED' 'F.C.A. P.I.N.O.S.' 'ABORTION'
 'CRIMINAL MISCHIEF & RELATED OF' 'OFFENSES AGAINST PUBLIC ADMINI'
 'OTHER OFFENSES RELATED TO THEF' 'OFF. AGNST PUB ORD SENSBLTY &'
 'UNAUTHORIZED USE OF A VEHICLE' 'AGRICULTURE & MRKTS LAW-UNCLASSIFIED'
 'MURDER & NON-NEGL. MANSLAUGHTE' 'NYS LAWS-UNCLASSIFIED FELONY'
 'HOMICIDE-NEGLIGENT,UNCLASSIFIE' 'OTHER STATE LAWS (NON PENAL LA'
 'ENDAN WELFARE INCOMP' 'THEFT OF SERVICES'
 'CHILD ABANDONMENT/NON SUPPORT' 'CANNABIS RELATED OFFENSES'
 'UNDER THE INFLUENCE, DRUGS' 'KIDNAPPING' 'NEW YORK CITY HEALTH CODE'
 'LOITERING/GAMBLING (CARDS, DIC' 'DISRUPTION OF A RELIGIOUS SERV'
 'UNLAWFUL POSS. WEAP. ON SCHOOL' 'NYS LAWS-UNCLASSIFIED VIOLATION'
 'ADMINISTRATIVE CODES' 'FELONY SEX CRIMES'
 'KIDNAPPING AND RELATED OFFENSES' 'LOITERING,BEGGING']
Total unique elements in offensive description is: 88

In [ ]:
percentage_per_category = filtered_df['OFNS_DESC'].value_counts(normalize=True) * 100
print(percentage_per_category)

ASSAULT 3 & RELATED OFFENSES       16.124427
PETIT LARCENY                      10.181852
FELONY ASSAULT                      9.809890
MISCELLANEOUS PENAL LAW             6.654562
DANGEROUS DRUGS                     6.493814
                                     ...
NEW YORK CITY HEALTH CODE           0.000529
DISRUPTION OF A RELIGIOUS SERV      0.000529
UNLAWFUL POSS. WEAP. ON SCHOOL      0.000353
NYS LAWS-UNCLASSIFIED VIOLATION     0.000176
KIDNAPPING AND RELATED OFFENSES     0.000176
Name: OFNS_DESC, Length: 66, dtype: float64

#### Due to large number of unique values will be keepin as object type as opposed to categorical

In [ ]:
filtered_df['ARREST_BORO'].unique()

array(['B', 'M', 'Q', 'K', 'S'], dtype=object)

In [ ]:
filtered_df['ARREST_BORO'] = filtered_df['ARREST_BORO'].astype('category')

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/1249147181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['ARREST_BORO'] = filtered_df['ARREST_BORO'].astype('category')

In [ ]:
filtered_df['ARREST_PRECINCT'].unique()

array([ 41,  19, 109, 115,  46, 112,  45,   5,  44,  17, 113,  40, 110,
        76,  14,  60,  84,  24,  42,  25, 101, 111,  75,  77,  52,  20,
        34,  49, 121,  28,  48, 114,  69, 120,  62, 107,  61,  10,  50,
        66,  43, 123,  83, 105,   6,   1,  33,  68,  18, 122,  23,  47,
        81,  79,  88, 100,  26,  71,  13,  94, 103,   7,  67,  22,  73,
        63, 104,  78,  90,  70, 102,  32,  30, 106,   9,  72, 108])

In [ ]:
filtered_df['ARREST_PRECINCT'] = filtered_df['ARREST_PRECINCT'].astype('category')

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/1042203467.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['ARREST_PRECINCT'] = filtered_df['ARREST_PRECINCT'].astype('category')

In [ ]:
print(filtered_df['ARREST_BORO'].unique())

['B', 'M', 'Q', 'K', 'S']
Categories (5, object): ['B', 'K', 'M', 'Q', 'S']

In [ ]:
#Originally brooklyn was under letter K as brooklyn is also known as Kings County

boro_mapping = {
    'M': 'Manhattan',
    'K': 'Brooklyn',
    'Q': 'Queens',
    'B': 'Bronx',
    'S': 'Staten Island'
}

# Rename categories using the dictionary
filtered_df['ARREST_BORO'] = filtered_df['ARREST_BORO'].cat.rename_categories(boro_mapping)

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/2829287588.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['ARREST_BORO'] = filtered_df['ARREST_BORO'].cat.rename_categories(boro_mapping)

In [ ]:
filtered_df['ARREST_BORO']

97             Bronx
99             Bronx
100        Manhattan
102           Queens
106           Queens
             ...
1923081        Bronx
1923082    Manhattan
1923085       Queens
1923091        Bronx
1923098        Bronx
Name: ARREST_BORO, Length: 566724, dtype: category
Categories (5, object): ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island']

In [ ]:
filtered_df['PERP_SEX'].unique()

array(['M', 'F', 'U'], dtype=object)

In [ ]:
sex_mapping = {
    'M': 'Male',
    'F': 'Female'
}

# Convert 'PERP_SEX' to categorical data type
filtered_df['PERP_SEX'] = filtered_df['PERP_SEX'].astype('category')

# Rename categories using the dictionary
filtered_df['PERP_SEX'] = filtered_df['PERP_SEX'].cat.rename_categories(sex_mapping)

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/1707558394.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['PERP_SEX'] = filtered_df['PERP_SEX'].astype('category')
/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/1707558394.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['PERP_SEX'] = filtered_df['PERP_SEX'].cat.rename_categories(sex_mapping)

In [ ]:
filtered_df['PERP_RACE'].unique()

array(['WHITE HISPANIC', 'BLACK', 'WHITE', 'UNKNOWN',
       'ASIAN / PACIFIC ISLANDER', 'BLACK HISPANIC',
       'AMERICAN INDIAN/ALASKAN NATIVE'], dtype=object)

In [ ]:
filtered_df['PERP_RACE'] = filtered_df['PERP_RACE'].astype('category')

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/4117879870.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['PERP_RACE'] = filtered_df['PERP_RACE'].astype('category')

In [ ]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 566724 entries, 97 to 1923098
Data columns (total 19 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ARREST_KEY         566724 non-null  int64
 1   ARREST_DATE        566724 non-null  datetime64[ns]
 2   PD_CD              566724 non-null  float64
 3   PD_DESC            566724 non-null  object
 4   KY_CD              566724 non-null  float64
 5   OFNS_DESC          566724 non-null  object
 6   LAW_CODE           566724 non-null  object
 7   LAW_CAT_CD         566724 non-null  object
 8   ARREST_BORO        566724 non-null  category
 9   ARREST_PRECINCT    566724 non-null  category
 10  JURISDICTION_CODE  566724 non-null  float64
 11  AGE_GROUP          566724 non-null  object
 12  PERP_SEX           566724 non-null  category
 13  PERP_RACE          566724 non-null  category
 14  X_COORD_CD         566724 non-null  float64
 15  Y_COORD_CD         566724 non-null  float64
 16  Latitude           566724 non-null  float64
 17  Longitude          566724 non-null  float64
 18  Lon_Lat            566724 non-null  object
dtypes: category(4), datetime64[ns](1), float64(7), int64(1), object(6)
memory usage: 71.3+ MB

In [ ]:
filtered_df['LAW_CAT_CD'].unique()

array(['F', 'M', 'V', 'I', '9'], dtype=object)

In [ ]:
print(filtered_df.loc[filtered_df['LAW_CAT_CD'] == 'M']) #Misdomener

         ARREST_KEY ARREST_DATE  PD_CD                           PD_DESC  \
102       234719585  2021-10-09  464.0                          JOSTLING
909599    242341589  2022-03-19  339.0    LARCENY,PETIT FROM OPEN AREAS,
912715    239390820  2022-01-19  759.0    PUBLIC ADMINISTATION,UNCLASS M
913298    252341616  2022-10-11  101.0                         ASSAULT 3
917283    242815102  2022-03-29  101.0                         ASSAULT 3
...             ...         ...    ...                               ...
1923040   223456995  2021-01-23  969.0    TRAFFIC,UNCLASSIFIED INFRACTIO
1923052   223191657  2021-01-17  259.0  CRIMINAL MISCHIEF,UNCLASSIFIED 4
1923079   225119897  2021-03-04  750.0                  RESISTING ARREST
1923082   223030255  2021-01-13  511.0    CONTROLLED SUBSTANCE, POSSESSI
1923091   224965052  2021-02-28  511.0    CONTROLLED SUBSTANCE, POSSESSI

         KY_CD                       OFNS_DESC    LAW_CODE LAW_CAT_CD  \
102      230.0                        JOSTLING  PL 1652501          M
909599   341.0                   PETIT LARCENY  PL 1552500          M
912715   359.0  OFFENSES AGAINST PUBLIC ADMINI  PL 1950500          M
913298   344.0    ASSAULT 3 & RELATED OFFENSES  PL 1200001          M
917283   344.0    ASSAULT 3 & RELATED OFFENSES  PL 1200001          M
...        ...                             ...         ...        ...
1923040  881.0        OTHER TRAFFIC INFRACTION  VTL051101A          M
1923052  351.0  CRIMINAL MISCHIEF & RELATED OF  PL 1450001          M
1923079  359.0  OFFENSES AGAINST PUBLIC ADMINI  PL 2053000          M
1923082  235.0                 DANGEROUS DRUGS  PL 2200300          M
1923091  235.0                 DANGEROUS DRUGS  PL 2200300          M

        ARREST_BORO ARREST_PRECINCT  JURISDICTION_CODE AGE_GROUP PERP_SEX  \
102          Queens             109                1.0     25-44     Male
909599     Brooklyn              60                0.0     25-44     Male
912715        Bronx              42                0.0     18-24     Male
913298     Brooklyn              76                0.0     25-44     Male
917283     Brooklyn              77                2.0     25-44     Male
...             ...             ...                ...       ...      ...
1923040    Brooklyn              94                0.0     45-64     Male
1923052      Queens             100                0.0     18-24     Male
1923079    Brooklyn              70                0.0     25-44     Male
1923082   Manhattan               9                0.0     25-44   Female
1923091       Bronx              46                0.0     45-64     Male

                        PERP_RACE  X_COORD_CD  Y_COORD_CD   Latitude  \
102                         BLACK   1031307.0    216054.0  40.759578
909599                      WHITE    988076.0    151540.0  40.582620
912715                      BLACK   1008690.0    238862.0  40.822271
913298             WHITE HISPANIC    984110.0    188363.0  40.683691
917283                      BLACK   1003811.0    183892.0  40.671398
...                           ...         ...         ...        ...
1923040                     BLACK    998787.0    202952.0  40.723729
1923052                     BLACK   1032564.0    151732.0  40.583022
1923079                     BLACK    991591.0    169049.0  40.630682
1923082  ASIAN / PACIFIC ISLANDER    989559.0    202085.0  40.721360
1923091            WHITE HISPANIC   1011511.0    248284.0  40.848123

         Longitude                                        Lon_Lat
102     -73.830141  POINT (-73.83014069999997 40.759577798000066)
909599  -73.986223                    POINT (-73.986223 40.58262)
912715  -73.911698      POINT (-73.911697780277 40.8222710411331)
913298  -74.000504                   POINT (-74.000504 40.683691)
917283  -73.929483                   POINT (-73.929483 40.671398)
...            ...                                            ...
1923040 -73.947556   POINT (-73.94755577299998 40.72372934300005)
1923052 -73.826064   POINT (-73.82606436199995 40.58302191400003)
1923079 -73.973554   POINT (-73.97355396999995 40.63068215900006)
1923082 -73.980849   POINT (-73.98084865299995 40.72135998800008)
1923091 -73.901467        POINT (-73.901466999 40.84812344200003)

[308489 rows x 19 columns]

In [ ]:
print(df.loc[df['LAW_CAT_CD'] == 'F']) #Felony

         ARREST_KEY ARREST_DATE  PD_CD  \
0         220756993  2020-11-19  155.0
1         221995093  2020-12-18  177.0
2         221558560  2020-12-09  157.0
4         219517698  2020-10-21  153.0
5         218151681  2020-09-21  157.0
...             ...         ...    ...
5725511    55927622  2009-01-22  760.0
5725512    56981119  2009-02-12  104.0
5725516    55869459  2009-01-20  244.0
5725519    58924345  2009-02-19  397.0
5725520    59093573  2009-02-25  779.0

                                           PD_DESC  KY_CD  \
0                                           RAPE 2  104.0
1                                     SEXUAL ABUSE  116.0
2                                           RAPE 1  104.0
4                                           RAPE 3  104.0
5                                           RAPE 1  104.0
...                                            ...    ...
5725511              BRIBERY,PUBLIC ADMINISTRATION  126.0
5725512             VEHICULAR ASSAULT (INTOX DRIVE  126.0
5725516         BURGLARY,UNCLASSIFIED,UNKNOWN TIME  107.0
5725519            ROBBERY,UNCLASSIFIED,OPEN AREAS  105.0
5725520  PUBLIC ADMINISTRATION,UNCLASSIFIED FELONY  126.0

                       OFNS_DESC    LAW_CODE LAW_CAT_CD ARREST_BORO  \
0                           RAPE  PL 1303001          F           B
1                     SEX CRIMES  PL 1306503          F           K
2                           RAPE  PL 1303501          F           S
4                           RAPE  PL 1302502          F           Q
5                           RAPE  PL 1303501          F           K
...                          ...         ...        ...         ...
5725511  MISCELLANEOUS PENAL LAW  PL 2154002          F           M
5725512  MISCELLANEOUS PENAL LAW  PL 1200301          F           B
5725516                 BURGLARY  PL 1402000          F           Q
5725519                  ROBBERY  PL 1601504          F           B
5725520  MISCELLANEOUS PENAL LAW  PL 215510B          F           M

         ARREST_PRECINCT  JURISDICTION_CODE AGE_GROUP PERP_SEX  \
0                     41                0.0     18-24        M
1                     84                0.0     45-64        M
2                    120                0.0       <18        M
4                    112                0.0     25-44        M
5                     77                0.0     25-44        M
...                  ...                ...       ...      ...
5725511               33                0.0     45-64        M
5725512               43                0.0     18-24        M
5725516              108                0.0     25-44        M
5725519               44                0.0       <18        M
5725520               30                0.0     25-44        F

              PERP_RACE  X_COORD_CD  Y_COORD_CD   Latitude  Longitude  \
0                 BLACK   1013232.0    236725.0  40.816392 -73.895296
1                 WHITE    989013.0    192652.0  40.695469 -73.982825
2                 BLACK    962748.0    174174.0  40.644726 -74.077483
4        WHITE HISPANIC   1025420.0    202485.0  40.722364 -73.851474
5                 BLACK   1003606.0    185050.0  40.674583 -73.930222
...                 ...         ...         ...        ...        ...
5725511  BLACK HISPANIC   1001058.0    246206.0  40.842446 -73.939254
5725512         UNKNOWN   1020183.0    239283.0  40.823387 -73.870170
5725516  WHITE HISPANIC   1005231.0    208496.0  40.738933 -73.924290
5725519           BLACK   1006032.0    243764.0  40.835733 -73.921285
5725520           WHITE    999110.0    239415.0  40.823810 -73.946310

                                               Lon_Lat
0        POINT (-73.89529641399997 40.816391847000034)
1         POINT (-73.98282507899995 40.69546894100006)
2         POINT (-74.07748315899995 40.64472613100002)
4         POINT (-73.85147389399998 40.72236368700004)
5         POINT (-73.93022154099998 40.67458330800008)
...                                                ...
5725511  POINT (-73.93925439599997 40.842446027000044)
5725512         POINT (-73.87017045 40.82338729100008)
5725516  POINT (-73.92429023899997 40.738933326000044)
5725519   POINT (-73.92128542599994 40.83573258000007)
5725520        POINT (-73.946309849 40.82381017900008)

[1656633 rows x 19 columns]

In [ ]:
filtered_df.loc[filtered_df['LAW_CAT_CD'] == 'I'] #Traffic

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
966277,239605686,2022-01-24,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Manhattan,17,0.0,18-24,Male,WHITE HISPANIC,992253.0,214996.0,40.756789,-73.971110,POINT (-73.97111 40.756789)
967591,240288473,2022-02-08,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Queens,113,0.0,18-24,Male,ASIAN / PACIFIC ISLANDER,1046399.0,187126.0,40.680077,-73.775929,POINT (-73.775929 40.680077)
968608,239518994,2022-01-21,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL1192AI1,I,Manhattan,23,0.0,25-44,Male,BLACK HISPANIC,998751.0,226901.0,40.789463,-73.947634,POINT (-73.9476340039424 40.7894632995555)
969165,241301568,2022-02-27,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL1192AI1,I,Manhattan,34,0.0,25-44,Male,BLACK HISPANIC,1003421.0,250627.0,40.854569,-73.930699,POINT (-73.930699 40.854569)
970510,239633091,2022-01-25,968.0,UNLICENSED OPERATOR,880.0,MOVING INFRACTIONS,VTL0509001,I,Bronx,48,0.0,25-44,Female,BLACK,1013091.0,248744.0,40.849373,-73.895753,POINT (-73.89575271 40.84937269)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1909881,223177508,2021-01-17,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL1192AI1,I,Manhattan,5,0.0,25-44,Female,WHITE HISPANIC,985145.0,203571.0,40.725440,-73.996772,POINT (-73.99677244099996 40.72544024600006)
1915604,223526622,2021-01-25,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Queens,115,0.0,45-64,Male,WHITE HISPANIC,1018714.0,214946.0,40.756595,-73.875603,POINT (-73.87560301799994 40.756594678000056)
1917321,223662485,2021-01-28,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Bronx,43,0.0,45-64,Male,WHITE,1020183.0,239283.0,40.823387,-73.870170,POINT (-73.87017045 40.82338729100008)
1917428,223058908,2021-01-14,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Manhattan,1,0.0,45-64,Male,BLACK HISPANIC,982351.0,201758.0,40.720464,-74.006852,POINT (-74.00685220399998 40.720463840000036)
1918975,224317649,2021-02-13,968.0,UNLICENSED OPERATOR,880.0,MOVING INFRACTIONS,VTL0509001,I,Queens,104,0.0,25-44,Male,WHITE HISPANIC,1013482.0,194614.0,40.700807,-73.894576,POINT (-73.89457631799998 40.70080717800005)

In [ ]:
filtered_df.loc[filtered_df['LAW_CAT_CD'] == '9']

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
1149345,261415958,2023-01-05,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,102,0.0,25-44,Male,WHITE,1032501.0,198800.0,40.712206,-73.825952,POINT (-73.825952 40.712206)
1150243,261786919,2023-01-12,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3.0,25-44,Male,BLACK,1046315.0,187088.0,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
1151925,262820315,2023-02-01,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,102,0.0,25-44,Female,WHITE,1032501.0,198800.0,40.712206,-73.825952,POINT (-73.825952 40.712206)
1155242,264051045,2023-02-22,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,102,0.0,25-44,Male,BLACK,1032501.0,198800.0,40.712206,-73.825952,POINT (-73.825952 40.712206)
1155487,264430516,2023-03-02,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,102,0.0,25-44,Female,BLACK,1031164.0,199399.0,40.713859,-73.830768,POINT (-73.830768 40.713859)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1391245,279504937,2023-12-26,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3.0,25-44,Female,ASIAN / PACIFIC ISLANDER,1046315.0,187088.0,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
1391590,278897966,2023-12-12,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3.0,25-44,Male,WHITE HISPANIC,1046315.0,187088.0,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
1391655,277114485,2023-11-07,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Manhattan,5,0.0,25-44,Female,BLACK,982682.0,199754.0,40.714957,-74.005654,POINT (-74.005654 40.714957)
1391824,278821522,2023-12-11,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3.0,25-44,Male,WHITE HISPANIC,1046315.0,187088.0,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
1392464,278821516,2023-12-11,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3.0,25-44,Female,WHITE HISPANIC,1046315.0,187088.0,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)

In [ ]:
law_cat = {
    'F': 'Felony',
    'M': 'Misdemeanor',
    'V': 'Violation',
    '9': 'Unclassified Violation',
    'I': 'Traffic'
}

# Convert 'PERP_SEX' to categorical data type
filtered_df['LAW_CAT_CD'] = filtered_df['LAW_CAT_CD'].astype('category')

# Rename categories using the dictionary
filtered_df['LAW_CAT_CD'] = filtered_df['LAW_CAT_CD'].cat.rename_categories(law_cat)

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/2818382704.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['LAW_CAT_CD'] = filtered_df['LAW_CAT_CD'].astype('category')
/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/2818382704.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['LAW_CAT_CD'] = filtered_df['LAW_CAT_CD'].cat.rename_categories(law_cat)

In [ ]:
filtered_df['JURISDICTION_CODE'].unique()

array([ 0.,  1., 72., 73.,  2.,  3., 71., 11., 97., 15., 14., 87.,  7.,
        4., 88., 69.,  9., 74., 85.,  6., 16., 13., 12., 79., 17., 52.,
       51.,  8., 76.])

In [ ]:
filtered_df['JURISDICTION_CODE'] = filtered_df['JURISDICTION_CODE'].astype('category')

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/3064594229.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['JURISDICTION_CODE'] = filtered_df['JURISDICTION_CODE'].astype('category')

In [ ]:
filtered_df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,Lon_Lat
97,236848384,2021-11-23,155.0,RAPE 2,104.0,RAPE,PL 1303001,Felony,Bronx,41,0.0,25-44,Male,WHITE HISPANIC,1013232.0,236725.0,40.816392,-73.895296,POINT (-73.89529641399997 40.816391847000034)
99,236341389,2021-11-16,157.0,RAPE 1,104.0,RAPE,PL 1303501,Felony,Bronx,41,0.0,25-44,Male,BLACK,1013232.0,236725.0,40.816392,-73.895296,POINT (-73.89529641399997 40.816391847000034)
100,233911057,2021-09-22,166.0,SODOMY 2,116.0,SEX CRIMES,PL 1304501,Felony,Manhattan,19,0.0,25-44,Male,BLACK,994276.0,218779.0,40.767177,-73.963807,POINT (-73.96380668299997 40.76717676000004)
102,234719585,2021-10-09,464.0,JOSTLING,230.0,JOSTLING,PL 1652501,Misdemeanor,Queens,109,1.0,25-44,Male,BLACK,1031307.0,216054.0,40.759578,-73.830141,POINT (-73.83014069999997 40.759577798000066)
106,234603111,2021-10-06,157.0,RAPE 1,104.0,RAPE,PL 1303501,Felony,Queens,115,0.0,25-44,Male,WHITE HISPANIC,1018699.0,215043.0,40.756861,-73.875657,POINT (-73.87565666399996 40.75686097700003)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1923081,223988764,2021-02-05,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,Felony,Bronx,44,0.0,18-24,Male,WHITE HISPANIC,1006537.0,244511.0,40.837782,-73.919458,POINT (-73.91945797099999 40.83778161800007)
1923082,223030255,2021-01-13,511.0,"CONTROLLED SUBSTANCE, POSSESSI",235.0,DANGEROUS DRUGS,PL 2200300,Misdemeanor,Manhattan,9,0.0,25-44,Female,ASIAN / PACIFIC ISLANDER,989559.0,202085.0,40.721360,-73.980849,POINT (-73.98084865299995 40.72135998800008)
1923085,224261923,2021-02-11,268.0,CRIMINAL MIS 2 & 3,121.0,CRIMINAL MISCHIEF & RELATED OF,PL 1450502,Felony,Queens,108,15.0,45-64,Male,WHITE,998831.0,209137.0,40.740706,-73.947384,POINT (-73.94738363099998 40.74070557800008)
1923091,224965052,2021-02-28,511.0,"CONTROLLED SUBSTANCE, POSSESSI",235.0,DANGEROUS DRUGS,PL 2200300,Misdemeanor,Bronx,46,0.0,45-64,Male,WHITE HISPANIC,1011511.0,248284.0,40.848123,-73.901467,POINT (-73.901466999 40.84812344200003)
1923098,224307694,2021-02-12,503.0,"CONTROLLED SUBSTANCE,INTENT TO",117.0,DANGEROUS DRUGS,PL 2201601,Felony,Bronx,46,0.0,25-44,Male,WHITE HISPANIC,1007160.0,247651.0,40.846398,-73.917196,POINT (-73.91719577199996 40.84639840500005)

In [ ]:
filtered_df['AGE_GROUP'] = filtered_df['AGE_GROUP'].astype('category')

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/1838199725.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['AGE_GROUP'] = filtered_df['AGE_GROUP'].astype('category')

In [ ]:
filtered_df['OFNS_DESC'].unique()

array(['RAPE', 'SEX CRIMES', 'JOSTLING', 'CRIMINAL MISCHIEF & RELATED OF',
       'DANGEROUS DRUGS', 'PETIT LARCENY', 'GRAND LARCENY',
       'OFFENSES AGAINST PUBLIC ADMINI', 'ASSAULT 3 & RELATED OFFENSES',
       'DANGEROUS WEAPONS', 'THEFT-FRAUD', 'FELONY ASSAULT', 'FORGERY',
       'OFFENSES INVOLVING FRAUD', 'ROBBERY',
       'POSSESSION OF STOLEN PROPERTY', 'OTHER OFFENSES RELATED TO THEF',
       'INTOXICATED & IMPAIRED DRIVING', 'VEHICLE AND TRAFFIC LAWS',
       'MISCELLANEOUS PENAL LAW', 'CRIMINAL TRESPASS', 'BURGLARY',
       'GRAND LARCENY OF MOTOR VEHICLE', 'OFFENSES AGAINST THE PERSON',
       'ARSON', 'OTHER TRAFFIC INFRACTION',
       'OFF. AGNST PUB ORD SENSBLTY &', 'UNAUTHORIZED USE OF A VEHICLE',
       'AGRICULTURE & MRKTS LAW-UNCLASSIFIED',
       'MURDER & NON-NEGL. MANSLAUGHTE', 'ADMINISTRATIVE CODE',
       'PROSTITUTION & RELATED OFFENSES', "BURGLAR'S TOOLS",
       'NYS LAWS-UNCLASSIFIED FELONY', 'OTHER STATE LAWS', 'FRAUDS',
       'HOMICIDE-NEGLIGENT,UNCLASSIFIE', 'INTOXICATED/IMPAIRED DRIVING',
       'OTHER STATE LAWS (NON PENAL LA', 'ANTICIPATORY OFFENSES',
       'HOMICIDE-NEGLIGENT-VEHICLE', 'FRAUDULENT ACCOSTING',
       'ALCOHOLIC BEVERAGE CONTROL LAW', 'ENDAN WELFARE INCOMP',
       'THEFT OF SERVICES', 'MOVING INFRACTIONS',
       'CHILD ABANDONMENT/NON SUPPORT', 'KIDNAPPING & RELATED OFFENSES',
       'CANNABIS RELATED OFFENSES', 'GAMBLING', 'HARRASSMENT 2',
       'OFFENSES AGAINST PUBLIC SAFETY', 'ESCAPE 3', 'KIDNAPPING',
       'OFFENSES RELATED TO CHILDREN', 'DISORDERLY CONDUCT',
       'NEW YORK CITY HEALTH CODE', 'PARKING OFFENSES',
       'OTHER STATE LAWS (NON PENAL LAW)',
       'LOITERING/GAMBLING (CARDS, DIC', 'DISRUPTION OF A RELIGIOUS SERV',
       'UNLAWFUL POSS. WEAP. ON SCHOOL',
       'NYS LAWS-UNCLASSIFIED VIOLATION', 'ADMINISTRATIVE CODES',
       'FELONY SEX CRIMES', 'KIDNAPPING AND RELATED OFFENSES'],
      dtype=object)

In [ ]:
#Changing to categorical for model usage down the line
filtered_df['OFNS_DESC'] = filtered_df['OFNS_DESC'].astype('category')

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/4096627976.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['OFNS_DESC'] = filtered_df['OFNS_DESC'].astype('category')

In [ ]:
unique_law_codes = filtered_df['LAW_CODE'].unique()
total_unique_law_codes = len(unique_law_codes)
print(f"Total unique law codes: {total_unique_law_codes}")
filtered_df['LAW_CODE'] = filtered_df['LAW_CODE'].astype('category')

Total unique law codes: 1386

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/2228161968.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['LAW_CODE'] = filtered_df['LAW_CODE'].astype('category')

In [ ]:
filtered_df['PD_DESC'].unique()
unique_pd_desc = filtered_df['PD_DESC'].unique()
total_unique_pd_desc = len(unique_pd_desc)
print(f"Total unique pd descriptions: {total_unique_pd_desc }")
filtered_df['PD_DESC'] = filtered_df['PD_DESC'].astype('category')

Total unique pd descriptions: 273

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/3597707800.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df['PD_DESC'] = filtered_df['PD_DESC'].astype('category')

In [ ]:
filtered_df.drop(columns=['ARREST_KEY','X_COORD_CD', 'Y_COORD_CD','ARREST_KEY','PD_CD'] ,axis=1, inplace=True)

/var/folders/18/920vt1r90t39q35zb6glj_6h0000gn/T/ipykernel_744/2395677207.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_df.drop(columns=['ARREST_KEY','X_COORD_CD', 'Y_COORD_CD','ARREST_KEY','PD_CD'] ,axis=1, inplace=True)

In [ ]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 566724 entries, 97 to 1923098
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ARREST_DATE        566724 non-null  datetime64[ns]
 1   PD_DESC            566724 non-null  category
 2   KY_CD              566724 non-null  float64
 3   OFNS_DESC          566724 non-null  category
 4   LAW_CODE           566724 non-null  category
 5   LAW_CAT_CD         566724 non-null  category
 6   ARREST_BORO        566724 non-null  category
 7   ARREST_PRECINCT    566724 non-null  category
 8   JURISDICTION_CODE  566724 non-null  category
 9   AGE_GROUP          566724 non-null  category
 10  PERP_SEX           566724 non-null  category
 11  PERP_RACE          566724 non-null  category
 12  Latitude           566724 non-null  float64
 13  Longitude          566724 non-null  float64
 14  Lon_Lat            566724 non-null  object
dtypes: category(10), datetime64[ns](1), float64(3), object(1)
memory usage: 48.6+ MB

In [ ]:
filtered_df.head()

,ARREST_DATE,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude,Lon_Lat
97,2021-11-23,RAPE 2,104.0,RAPE,PL 1303001,Felony,Bronx,41,0.0,25-44,Male,WHITE HISPANIC,40.816392,-73.895296,POINT (-73.89529641399997 40.816391847000034)
99,2021-11-16,RAPE 1,104.0,RAPE,PL 1303501,Felony,Bronx,41,0.0,25-44,Male,BLACK,40.816392,-73.895296,POINT (-73.89529641399997 40.816391847000034)
100,2021-09-22,SODOMY 2,116.0,SEX CRIMES,PL 1304501,Felony,Manhattan,19,0.0,25-44,Male,BLACK,40.767177,-73.963807,POINT (-73.96380668299997 40.76717676000004)
102,2021-10-09,JOSTLING,230.0,JOSTLING,PL 1652501,Misdemeanor,Queens,109,1.0,25-44,Male,BLACK,40.759578,-73.830141,POINT (-73.83014069999997 40.759577798000066)
106,2021-10-06,RAPE 1,104.0,RAPE,PL 1303501,Felony,Queens,115,0.0,25-44,Male,WHITE HISPANIC,40.756861,-73.875657,POINT (-73.87565666399996 40.75686097700003)

## I changed all object data types from Obj to category for both memory and ability to attempt to use modeling techniques down the line. for future refrence may just run a for loop from code below

for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = df[column].astype('category')

In [ ]:
filtered_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 566724 entries, 97 to 1923098
Data columns (total 15 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ARREST_DATE        566724 non-null  datetime64[ns]
 1   PD_DESC            566724 non-null  category
 2   KY_CD              566724 non-null  float64
 3   OFNS_DESC          566724 non-null  category
 4   LAW_CODE           566724 non-null  category
 5   LAW_CAT_CD         566724 non-null  category
 6   ARREST_BORO        566724 non-null  category
 7   ARREST_PRECINCT    566724 non-null  category
 8   JURISDICTION_CODE  566724 non-null  category
 9   AGE_GROUP          566724 non-null  category
 10  PERP_SEX           566724 non-null  category
 11  PERP_RACE          566724 non-null  category
 12  Latitude           566724 non-null  float64
 13  Longitude          566724 non-null  float64
 14  Lon_Lat            566724 non-null  object
dtypes: category(10), datetime64[ns](1), float64(3), object(1)
memory usage: 48.6+ MB

In [ ]:
filtered_df.to_csv('NYPD_arrest_data_2021-2023.csv',index= False)