In [2]:
pip install pandas

Collecting pandas
  Obtaining dependency information for pandas from https://files.pythonhosted.org/packages/ab/63/966db1321a0ad55df1d1fe51505d2cdae191b84c907974873817b0a6e849/pandas-2.2.2-cp311-cp311-win_amd64.whl.metadata
  Downloading pandas-2.2.2-cp311-cp311-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=1.23.2 in c:\users\thech\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (1.26.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\thech\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from pandas) (2.8.2)
Collecting pytz>=2020.1 (from pandas)
  Obtaining dependency information for pytz>=2020.1 from https://files.pythonhosted.org/packages/9c/3d/a121f284241f08268b21359bd425f7d4825cffc5ac5cd0e1b3d82ffd2b10/pytz-2024.1-py2.py3-none-any.whl.metadata
  Downloading pytz-2024.1-py2.py3-none-any.whl.metadata (22 kB)
Collecting tzdata>=2022.7 (from pandas)
  Obtaining dependency information for tzdata>=2022.7 from https://files.pythonhosted.org/packages/65/58/f9c9e6be752e9fcb8b6a0ee9fb87e6e7a1f6bcab2cdc73f02bb7ba91ada0/tzdata-2024.1-py2.py3-none-any.whl.metadata
  Downloading tzdata-2024.1-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\thech\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Downloading pandas-2.2.2-cp311-cp311-win_amd64.whl (11.6 MB)
   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/11.6 MB 1.3 MB/s eta 0:00:10
    --------------------------------------- 0.2/11.6 MB 2.4 MB/s eta 0:00:05
   - -------------------------------------- 0.5/11.6 MB 4.4 MB/s eta 0:00:03
   -- ------------------------------------- 0.8/11.6 MB 5.3 MB/s eta 0:00:03
   ---- ----------------------------------- 1.2/11.6 MB 5.8 MB/s eta 0:00:02
   ----- ---------------------------------- 1.5/11.6 MB 6.1 MB/s eta 0:00:02
   ------ --------------------------------- 1.9/11.6 MB 6.5 MB/s eta 0:00:02
   ------- -------------------------------- 2.3/11.6 MB 6.7 MB/s eta 0:00:02
   --------- ------------------------------ 2.7/11.6 MB 7.0 MB/s eta 0:00:02
   ---------- ----------------------------- 3.1/11.6 MB 7.1 MB/s eta 0:00:02
   ----------- ---------------------------- 3.5/11.6 MB 7.2 MB/s eta 0:00:02
   ------------- -------------------------- 3.9/11.6 MB 7.3 MB/s eta 0:00:02
   -------------- ------------------------- 4.2/11.6 MB 7.2 MB/s eta 0:00:02
   --------------- ------------------------ 4.5/11.6 MB 7.2 MB/s eta 0:00:01
   ---------------- ----------------------- 4.8/11.6 MB 7.3 MB/s eta 0:00:01
   ----------------- ---------------------- 5.1/11.6 MB 7.3 MB/s eta 0:00:01
   ------------------ --------------------- 5.5/11.6 MB 7.3 MB/s eta 0:00:01
   -------------------- ------------------- 5.8/11.6 MB 7.2 MB/s eta 0:00:01
   --------------------- ------------------ 6.2/11.6 MB 7.4 MB/s eta 0:00:01
   ---------------------- ----------------- 6.6/11.6 MB 7.3 MB/s eta 0:00:01
   ------------------------ --------------- 7.0/11.6 MB 7.4 MB/s eta 0:00:01
   ------------------------- -------------- 7.4/11.6 MB 7.5 MB/s eta 0:00:01
   -------------------------- ------------- 7.8/11.6 MB 7.5 MB/s eta 0:00:01
   ---------------------------- ----------- 8.3/11.6 MB 7.6 MB/s eta 0:00:01
   ----------------------------- ---------- 8.7/11.6 MB 7.6 MB/s eta 0:00:01
   ------------------------------- -------- 9.1/11.6 MB 7.6 MB/s eta 0:00:01
   -------------------------------- ------- 9.4/11.6 MB 7.6 MB/s eta 0:00:01
   --------------------------------- ------ 9.8/11.6 MB 7.7 MB/s eta 0:00:01
   ---------------------------------- ----- 10.1/11.6 MB 7.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.4/11.6 MB 7.9 MB/s eta 0:00:01
   ------------------------------------- -- 10.8/11.6 MB 8.0 MB/s eta 0:00:01
   -------------------------------------- - 11.1/11.6 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------  11.5/11.6 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------  11.6/11.6 MB 8.0 MB/s eta 0:00:01
   ---------------------------------------- 11.6/11.6 MB 7.6 MB/s eta 0:00:00
Downloading pytz-2024.1-py2.py3-none-any.whl (505 kB)
   ---------------------------------------- 0.0/505.5 kB ? eta -:--:--
   --------------------------- ----------- 358.4/505.5 kB 10.9 MB/s eta 0:00:01
   ---------------------------------------- 505.5/505.5 kB 7.9 MB/s eta 0:00:00
Downloading tzdata-2024.1-py2.py3-none-any.whl (345 kB)
   ---------------------------------------- 0.0/345.4 kB ? eta -:--:--
   ----------------------- ---------------- 204.8/345.4 kB 4.2 MB/s eta 0:00:01
   ---------------------------------------- 345.4/345.4 kB 4.3 MB/s eta 0:00:00
Installing collected packages: pytz, tzdata, pandas
Successfully installed pandas-2.2.2 pytz-2024.1 tzdata-2024.1
Note: you may need to restart the kernel to use updated packages.

In [3]:
import numpy as np 
import pandas as pd

In [5]:
df = pd.read_csv('NYPD_Arrest_Data__Year_to_Date_.csv')

In [6]:
df.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,280255493,01/10/2024,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,F,M,26,0,<18,M,BLACK,996342,236149,40.814845,-73.956312,POINT (-73.956312 40.814845)
1,279805419,01/02/2024,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,77,0,25-44,M,WHITE HISPANIC,1003509,185018,40.674496,-73.930571,POINT (-73.9305713255961 40.6744956865259)
2,279895750,01/03/2024,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,106,0,65+,F,WHITE,1026836,180689,40.662526,-73.846499,POINT (-73.846499 40.662526)
3,280809090,01/19/2024,511.0,"CONTROLLED SUBSTANCE, POSSESSI",235.0,DANGEROUS DRUGS,PL 2200300,M,B,49,0,45-64,M,BLACK,1027430,251104,40.855793,-73.843908,POINT (-73.843908 40.855793)
4,280357135,01/11/2024,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,K,81,2,25-44,F,BLACK,1002457,192292,40.694456,-73.934343,POINT (-73.934343 40.694456)

### Column Desc Decide later if this is worth keeping

Arrest Key

PD CD

KY CD

Law Code

Law Cat

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63621 entries, 0 to 63620
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ARREST_KEY                63621 non-null  int64
 1   ARREST_DATE               63621 non-null  object
 2   PD_CD                     63619 non-null  float64
 3   PD_DESC                   63621 non-null  object
 4   KY_CD                     63612 non-null  float64
 5   OFNS_DESC                 63621 non-null  object
 6   LAW_CODE                  63621 non-null  object
 7   LAW_CAT_CD                63219 non-null  object
 8   ARREST_BORO               63621 non-null  object
 9   ARREST_PRECINCT           63621 non-null  int64
 10  JURISDICTION_CODE         63621 non-null  int64
 11  AGE_GROUP                 63621 non-null  object
 12  PERP_SEX                  63621 non-null  object
 13  PERP_RACE                 63621 non-null  object
 14  X_COORD_CD                63621 non-null  int64
 15  Y_COORD_CD                63621 non-null  int64
 16  Latitude                  63621 non-null  float64
 17  Longitude                 63621 non-null  float64
 18  New Georeferenced Column  63621 non-null  object
dtypes: float64(4), int64(5), object(10)
memory usage: 9.2+ MB

### Checking for Missing/Duplicate Values

In [30]:
df.isna().sum()

ARREST_KEY                    0
ARREST_DATE                   0
PD_CD                         2
PD_DESC                       0
KY_CD                         9
OFNS_DESC                     0
LAW_CODE                      0
LAW_CAT_CD                  402
ARREST_BORO                   0
ARREST_PRECINCT               0
JURISDICTION_CODE             0
AGE_GROUP                     0
PERP_SEX                      0
PERP_RACE                     0
X_COORD_CD                    0
Y_COORD_CD                    0
Latitude                      0
Longitude                     0
New Georeferenced Column      0
dtype: int64

In [7]:
missing_percentage = (df['PD_CD'].isnull().sum() / len(df['PD_CD'])) * 100
print("Percentage of missing values in 'PD_CD' column:", missing_percentage)

Percentage of missing values in 'PD_CD' column: 0.0031436161016016725

In [8]:
missing_percentage = (df['KY_CD'].isnull().sum() / len(df['KY_CD'])) * 100
print("Percentage of missing values in 'KY_CD' column:", missing_percentage)

Percentage of missing values in 'KY_CD' column: 0.014146272457207527

In [10]:
missing_percentage = (df['LAW_CAT_CD'].isnull().sum() / len(df['LAW_CAT_CD'])) * 100
print("Percentage of missing values in 'LAW_CAT' column:", missing_percentage)

Percentage of missing values in 'LAW_CAT' column: 0.6318668364219362

In [11]:
misisng_KY_CD_rows = df[df['KY_CD'].isna()]
misisng_KY_CD_rows.head(12)

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
8,280961365,01/23/2024,NaN,(null),NaN,(null),(null),(null),M,5,97,25-44,M,BLACK,983903,200257,40.716337,-74.001251,POINT (-74.001251 40.716337)
5331,281035905,01/24/2024,777.0,(null),NaN,(null),PL 1950200,F,K,67,0,45-64,F,WHITE,997897,175676,40.648859,-73.950820,POINT (-73.95082 40.648859)
10056,280660228,01/17/2024,660.0,(null),NaN,(null),PL 2407800,M,B,42,0,<18,M,WHITE HISPANIC,1010967,238733,40.821903,-73.903466,POINT (-73.903466 40.821903)
20633,280346962,01/11/2024,660.0,(null),NaN,(null),PL 2407800,M,K,75,0,<18,M,WHITE HISPANIC,1013001,184766,40.673773,-73.896350,POINT (-73.89635 40.673773)
34105,281444571,01/31/2024,660.0,(null),NaN,(null),PL 2407900,M,M,18,0,25-44,F,BLACK,987171,218109,40.765336,-73.989454,POINT (-73.989454 40.765336)
39425,282534026,02/21/2024,777.0,(null),NaN,(null),PL 1950200,F,K,67,0,45-64,M,BLACK,997897,175676,40.648859,-73.950820,POINT (-73.95082 40.648859)
46307,282228504,02/14/2024,810.0,(null),NaN,(null),PL 2702100,M,K,67,0,25-44,M,ASIAN / PACIFIC ISLANDER,1006328,177267,40.653207,-73.920430,POINT (-73.92043 40.653207)
51782,284173781,03/22/2024,777.0,(null),NaN,(null),PL 1950200,F,B,40,0,45-64,F,WHITE,1005040,234533,40.810391,-73.924895,POINT (-73.924895 40.810391)
56233,283941614,03/18/2024,NaN,(null),NaN,(null),(null),(null),K,67,0,25-44,M,BLACK,998216,176711,40.651696,-73.949669,POINT (-73.94966875535633 40.65169649424705)

In [28]:
total_rows = len(df)
total_missing_count = df.isnull().sum()

for column, missing_count in total_missing_count.items():
    if missing_count > 0:
        missing_percentage = (missing_count / total_rows) * 100
        print(f"Percentage of missing values in '{column}' column: {missing_percentage:.2f}%")
        
total_missing_percentage = (total_missing_count.sum().sum() / (total_rows * len(df.columns))) * 100
print(f"Total percentage of missing values: {total_missing_percentage:.2f}%")

Percentage of missing values in 'PD_CD' column: 0.00%
Percentage of missing values in 'KY_CD' column: 0.01%
Percentage of missing values in 'LAW_CAT_CD' column: 0.63%
Total percentage of missing values: 0.03%

#CHECK THE ABOVE NUMBER THEY DONT ADD UP BUT DROP ALL NULL VALUES

In [31]:
df.dropna(inplace=True)

### Appropriating Data Types

In [32]:
df['ARREST_DATE'] = pd.to_datetime(df['ARREST_DATE'])

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 63210 entries, 0 to 63620
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ARREST_KEY                63210 non-null  int64
 1   ARREST_DATE               63210 non-null  datetime64[ns]
 2   PD_CD                     63210 non-null  float64
 3   PD_DESC                   63210 non-null  object
 4   KY_CD                     63210 non-null  float64
 5   OFNS_DESC                 63210 non-null  object
 6   LAW_CODE                  63210 non-null  object
 7   LAW_CAT_CD                63210 non-null  object
 8   ARREST_BORO               63210 non-null  object
 9   ARREST_PRECINCT           63210 non-null  int64
 10  JURISDICTION_CODE         63210 non-null  int64
 11  AGE_GROUP                 63210 non-null  object
 12  PERP_SEX                  63210 non-null  object
 13  PERP_RACE                 63210 non-null  object
 14  X_COORD_CD                63210 non-null  int64
 15  Y_COORD_CD                63210 non-null  int64
 16  Latitude                  63210 non-null  float64
 17  Longitude                 63210 non-null  float64
 18  New Georeferenced Column  63210 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(5), object(9)
memory usage: 9.6+ MB

In [35]:
df['LAW_CAT_CD'].describe()

count     63210
unique        5
top           M
freq      35576
Name: LAW_CAT_CD, dtype: object

In [36]:
df['LAW_CAT_CD'].unique()

array(['F', 'M', 'V', '9', 'I'], dtype=object)

In [44]:
df['OFNS_DESC'].unique()[0]

TypeError: 'int' object is not callable

In [43]:
percentage_per_category = df['OFNS_DESC'].value_counts(normalize=True) * 100
print(percentage_per_category)

OFNS_DESC
ASSAULT 3 & RELATED OFFENSES            14.174972
PETIT LARCENY                           10.324316
FELONY ASSAULT                           8.365765
DANGEROUS DRUGS                          7.487739
MISCELLANEOUS PENAL LAW                  6.315456
VEHICLE AND TRAFFIC LAWS                 6.206296
GRAND LARCENY                            4.853662
ROBBERY                                  4.659073
CRIMINAL MISCHIEF & RELATED OF           4.456573
DANGEROUS WEAPONS                        3.969309
OTHER OFFENSES RELATED TO THEF           3.523177
OFFENSES AGAINST PUBLIC ADMINI           3.133998
BURGLARY                                 2.529663
OFFENSES INVOLVING FRAUD                 2.189527
SEX CRIMES                               2.187945
FORGERY                                  2.045562
OFF. AGNST PUB ORD SENSBLTY &            1.800348
POSSESSION OF STOLEN PROPERTY            1.683278
CRIMINAL TRESPASS                        1.205505
OTHER TRAFFIC INFRACTION                 1.118494
INTOXICATED & IMPAIRED DRIVING           1.010916
GRAND LARCENY OF MOTOR VEHICLE           0.889100
OTHER STATE LAWS                         0.802088
OFFENSES AGAINST THE PERSON              0.639139
NYS LAWS-UNCLASSIFIED FELONY             0.631229
MURDER & NON-NEGL. MANSLAUGHTE           0.598007
DISORDERLY CONDUCT                       0.498339
FRAUDS                                   0.409745
BURGLAR'S TOOLS                          0.286347
RAPE                                     0.278437
UNAUTHORIZED USE OF A VEHICLE            0.238886
CANNABIS RELATED OFFENSES                0.193007
OTHER STATE LAWS (NON PENAL LA           0.162949
PROSTITUTION & RELATED OFFENSES          0.148711
GAMBLING                                 0.112324
INTOXICATED/IMPAIRED DRIVING             0.107578
ALCOHOLIC BEVERAGE CONTROL LAW           0.088594
THEFT-FRAUD                              0.083847
OFFENSES AGAINST PUBLIC SAFETY           0.080683
ADMINISTRATIVE CODE                      0.077519
THEFT OF SERVICES                        0.066445
JOSTLING                                 0.055371
ARSON                                    0.052207
KIDNAPPING & RELATED OFFENSES            0.045879
ENDAN WELFARE INCOMP                     0.039551
HARRASSMENT 2                            0.033223
HOMICIDE-NEGLIGENT,UNCLASSIFIE           0.026894
AGRICULTURE & MRKTS LAW-UNCLASSIFIED     0.025312
CHILD ABANDONMENT/NON SUPPORT            0.018984
MOVING INFRACTIONS                       0.017402
FRAUDULENT ACCOSTING                     0.015820
DISRUPTION OF A RELIGIOUS SERV           0.009492
ESCAPE 3                                 0.004746
OTHER STATE LAWS (NON PENAL LAW)         0.004746
HOMICIDE-NEGLIGENT-VEHICLE               0.003164
ANTICIPATORY OFFENSES                    0.003164
KIDNAPPING                               0.003164
OFFENSES RELATED TO CHILDREN             0.003164
ADMINISTRATIVE CODES                     0.001582
FORTUNE TELLING                          0.001582
Name: proportion, dtype: float64