In [159]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.10/site-packages (1.5.3)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /Users/los/Library/Python/3.10/lib/python/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/site-packages (from pandas) (2022.7.1)
Requirement already satisfied: six>=1.5 in /Users/los/Library/Python/3.10/lib/python/site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python3.10 -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [160]:
import numpy as np 
import pandas as pd

In [161]:
df = pd.read_csv('NYPD_Arrest_Data__Year_to_Date_.csv')

In [162]:
df.head()

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,280255493,01/10/2024,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,F,M,26,0,<18,M,BLACK,996342,236149,40.814845,-73.956312,POINT (-73.956312 40.814845)
1,279805419,01/02/2024,157.0,RAPE 1,104.0,RAPE,PL 1303501,F,K,77,0,25-44,M,WHITE HISPANIC,1003509,185018,40.674496,-73.930571,POINT (-73.9305713255961 40.6744956865259)
2,279895750,01/03/2024,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,M,Q,106,0,65+,F,WHITE,1026836,180689,40.662526,-73.846499,POINT (-73.846499 40.662526)
3,280809090,01/19/2024,511.0,"CONTROLLED SUBSTANCE, POSSESSI",235.0,DANGEROUS DRUGS,PL 2200300,M,B,49,0,45-64,M,BLACK,1027430,251104,40.855793,-73.843908,POINT (-73.843908 40.855793)
4,280357135,01/11/2024,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,F,K,81,2,25-44,F,BLACK,1002457,192292,40.694456,-73.934343,POINT (-73.934343 40.694456)

### Column Desc Decide later if this is worth keeping

Arrest Key

PD CD

KY CD

Law Code

Law Cat

In [163]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63621 entries, 0 to 63620
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ARREST_KEY                63621 non-null  int64
 1   ARREST_DATE               63621 non-null  object
 2   PD_CD                     63619 non-null  float64
 3   PD_DESC                   63621 non-null  object
 4   KY_CD                     63612 non-null  float64
 5   OFNS_DESC                 63621 non-null  object
 6   LAW_CODE                  63621 non-null  object
 7   LAW_CAT_CD                63219 non-null  object
 8   ARREST_BORO               63621 non-null  object
 9   ARREST_PRECINCT           63621 non-null  int64
 10  JURISDICTION_CODE         63621 non-null  int64
 11  AGE_GROUP                 63621 non-null  object
 12  PERP_SEX                  63621 non-null  object
 13  PERP_RACE                 63621 non-null  object
 14  X_COORD_CD                63621 non-null  int64
 15  Y_COORD_CD                63621 non-null  int64
 16  Latitude                  63621 non-null  float64
 17  Longitude                 63621 non-null  float64
 18  New Georeferenced Column  63621 non-null  object
dtypes: float64(4), int64(5), object(10)
memory usage: 9.2+ MB

### Checking for Missing/Duplicate Values

In [164]:
df.isna().sum()

ARREST_KEY                    0
ARREST_DATE                   0
PD_CD                         2
PD_DESC                       0
KY_CD                         9
OFNS_DESC                     0
LAW_CODE                      0
LAW_CAT_CD                  402
ARREST_BORO                   0
ARREST_PRECINCT               0
JURISDICTION_CODE             0
AGE_GROUP                     0
PERP_SEX                      0
PERP_RACE                     0
X_COORD_CD                    0
Y_COORD_CD                    0
Latitude                      0
Longitude                     0
New Georeferenced Column      0
dtype: int64

In [165]:
missing_percentage = (df['PD_CD'].isnull().sum() / len(df['PD_CD'])) * 100
print("Percentage of missing values in 'PD_CD' column:", missing_percentage)

Percentage of missing values in 'PD_CD' column: 0.0031436161016016725

In [166]:
missing_percentage = (df['KY_CD'].isnull().sum() / len(df['KY_CD'])) * 100
print("Percentage of missing values in 'KY_CD' column:", missing_percentage)

Percentage of missing values in 'KY_CD' column: 0.014146272457207527

In [167]:
missing_percentage = (df['LAW_CAT_CD'].isnull().sum() / len(df['LAW_CAT_CD'])) * 100
print("Percentage of missing values in 'LAW_CAT' column:", missing_percentage)

Percentage of missing values in 'LAW_CAT' column: 0.6318668364219362

In [168]:
misisng_KY_CD_rows = df[df['KY_CD'].isna()]
misisng_KY_CD_rows.head(12)

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
8,280961365,01/23/2024,NaN,(null),NaN,(null),(null),(null),M,5,97,25-44,M,BLACK,983903,200257,40.716337,-74.001251,POINT (-74.001251 40.716337)
5331,281035905,01/24/2024,777.0,(null),NaN,(null),PL 1950200,F,K,67,0,45-64,F,WHITE,997897,175676,40.648859,-73.950820,POINT (-73.95082 40.648859)
10056,280660228,01/17/2024,660.0,(null),NaN,(null),PL 2407800,M,B,42,0,<18,M,WHITE HISPANIC,1010967,238733,40.821903,-73.903466,POINT (-73.903466 40.821903)
20633,280346962,01/11/2024,660.0,(null),NaN,(null),PL 2407800,M,K,75,0,<18,M,WHITE HISPANIC,1013001,184766,40.673773,-73.896350,POINT (-73.89635 40.673773)
34105,281444571,01/31/2024,660.0,(null),NaN,(null),PL 2407900,M,M,18,0,25-44,F,BLACK,987171,218109,40.765336,-73.989454,POINT (-73.989454 40.765336)
39425,282534026,02/21/2024,777.0,(null),NaN,(null),PL 1950200,F,K,67,0,45-64,M,BLACK,997897,175676,40.648859,-73.950820,POINT (-73.95082 40.648859)
46307,282228504,02/14/2024,810.0,(null),NaN,(null),PL 2702100,M,K,67,0,25-44,M,ASIAN / PACIFIC ISLANDER,1006328,177267,40.653207,-73.920430,POINT (-73.92043 40.653207)
51782,284173781,03/22/2024,777.0,(null),NaN,(null),PL 1950200,F,B,40,0,45-64,F,WHITE,1005040,234533,40.810391,-73.924895,POINT (-73.924895 40.810391)
56233,283941614,03/18/2024,NaN,(null),NaN,(null),(null),(null),K,67,0,25-44,M,BLACK,998216,176711,40.651696,-73.949669,POINT (-73.94966875535633 40.65169649424705)

In [169]:
total_rows = len(df)
total_missing_count = df.isnull().sum()

for column, missing_count in total_missing_count.items():
    if missing_count > 0:
        missing_percentage = (missing_count / total_rows) * 100
        print(f"Percentage of missing values in '{column}' column: {missing_percentage:.2f}%")
        
total_missing_percentage = (total_missing_count.sum().sum() / (total_rows * len(df.columns))) * 100
print(f"Total percentage of missing values: {total_missing_percentage:.2f}%")

Percentage of missing values in 'PD_CD' column: 0.00%
Percentage of missing values in 'KY_CD' column: 0.01%
Percentage of missing values in 'LAW_CAT_CD' column: 0.63%
Total percentage of missing values: 0.03%

#CHECK THE ABOVE NUMBER THEY DONT ADD UP BUT DROP ALL NULL VALUES

In [170]:
df.dropna(inplace=True)

### Appropriating Data Types

In [171]:
df['ARREST_DATE'] = pd.to_datetime(df['ARREST_DATE'])

In [172]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63210 entries, 0 to 63620
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ARREST_KEY                63210 non-null  int64
 1   ARREST_DATE               63210 non-null  datetime64[ns]
 2   PD_CD                     63210 non-null  float64
 3   PD_DESC                   63210 non-null  object
 4   KY_CD                     63210 non-null  float64
 5   OFNS_DESC                 63210 non-null  object
 6   LAW_CODE                  63210 non-null  object
 7   LAW_CAT_CD                63210 non-null  object
 8   ARREST_BORO               63210 non-null  object
 9   ARREST_PRECINCT           63210 non-null  int64
 10  JURISDICTION_CODE         63210 non-null  int64
 11  AGE_GROUP                 63210 non-null  object
 12  PERP_SEX                  63210 non-null  object
 13  PERP_RACE                 63210 non-null  object
 14  X_COORD_CD                63210 non-null  int64
 15  Y_COORD_CD                63210 non-null  int64
 16  Latitude                  63210 non-null  float64
 17  Longitude                 63210 non-null  float64
 18  New Georeferenced Column  63210 non-null  object
dtypes: datetime64[ns](1), float64(4), int64(5), object(9)
memory usage: 9.6+ MB

In [173]:
df['LAW_CAT_CD'].describe()

count     63210
unique        5
top           M
freq      35576
Name: LAW_CAT_CD, dtype: object

In [174]:
df['LAW_CAT_CD'].unique()

array(['F', 'M', 'V', '9', 'I'], dtype=object)

In [175]:
print(df['OFNS_DESC'].unique())
print(f'Total unique elements in offensive description is: {len(df["OFNS_DESC"].unique())}')

['ROBBERY' 'RAPE' 'ASSAULT 3 & RELATED OFFENSES' 'DANGEROUS DRUGS'
 'FELONY ASSAULT' 'JOSTLING' 'ARSON' 'BURGLARY' 'DANGEROUS WEAPONS'
 'MISCELLANEOUS PENAL LAW' 'VEHICLE AND TRAFFIC LAWS' 'PETIT LARCENY'
 'CRIMINAL TRESPASS' 'GRAND LARCENY' 'OTHER OFFENSES RELATED TO THEF'
 'GRAND LARCENY OF MOTOR VEHICLE' 'CRIMINAL MISCHIEF & RELATED OF'
 'OFF. AGNST PUB ORD SENSBLTY &' 'OTHER TRAFFIC INFRACTION'
 'OFFENSES AGAINST PUBLIC ADMINI' 'DISORDERLY CONDUCT' 'SEX CRIMES'
 'FORGERY' 'NYS LAWS-UNCLASSIFIED FELONY' 'POSSESSION OF STOLEN PROPERTY'
 'OTHER STATE LAWS' 'MURDER & NON-NEGL. MANSLAUGHTE'
 'INTOXICATED & IMPAIRED DRIVING' 'OFFENSES INVOLVING FRAUD'
 'CANNABIS RELATED OFFENSES' 'OFFENSES AGAINST THE PERSON' 'FRAUDS'
 'ALCOHOLIC BEVERAGE CONTROL LAW' 'OTHER STATE LAWS (NON PENAL LA'
 'ENDAN WELFARE INCOMP' 'UNAUTHORIZED USE OF A VEHICLE'
 'ADMINISTRATIVE CODE' 'GAMBLING' 'PROSTITUTION & RELATED OFFENSES'
 "BURGLAR'S TOOLS" 'INTOXICATED/IMPAIRED DRIVING'
 'AGRICULTURE & MRKTS LAW-UNCLASSIFIED' 'THEFT OF SERVICES'
 'OFFENSES AGAINST PUBLIC SAFETY' 'THEFT-FRAUD'
 'KIDNAPPING & RELATED OFFENSES' 'HARRASSMENT 2' 'MOVING INFRACTIONS'
 'FRAUDULENT ACCOSTING' 'ESCAPE 3' 'ANTICIPATORY OFFENSES' 'KIDNAPPING'
 'HOMICIDE-NEGLIGENT,UNCLASSIFIE' 'CHILD ABANDONMENT/NON SUPPORT'
 'OTHER STATE LAWS (NON PENAL LAW)' 'ADMINISTRATIVE CODES'
 'HOMICIDE-NEGLIGENT-VEHICLE' 'DISRUPTION OF A RELIGIOUS SERV'
 'FORTUNE TELLING' 'OFFENSES RELATED TO CHILDREN']
Total unique elements in offensive description is: 60

In [176]:
percentage_per_category = df['OFNS_DESC'].value_counts(normalize=True) * 100
print(percentage_per_category)

ASSAULT 3 & RELATED OFFENSES            14.174972
PETIT LARCENY                           10.324316
FELONY ASSAULT                           8.365765
DANGEROUS DRUGS                          7.487739
MISCELLANEOUS PENAL LAW                  6.315456
VEHICLE AND TRAFFIC LAWS                 6.206296
GRAND LARCENY                            4.853662
ROBBERY                                  4.659073
CRIMINAL MISCHIEF & RELATED OF           4.456573
DANGEROUS WEAPONS                        3.969309
OTHER OFFENSES RELATED TO THEF           3.523177
OFFENSES AGAINST PUBLIC ADMINI           3.133998
BURGLARY                                 2.529663
OFFENSES INVOLVING FRAUD                 2.189527
SEX CRIMES                               2.187945
FORGERY                                  2.045562
OFF. AGNST PUB ORD SENSBLTY &            1.800348
POSSESSION OF STOLEN PROPERTY            1.683278
CRIMINAL TRESPASS                        1.205505
OTHER TRAFFIC INFRACTION                 1.118494
INTOXICATED & IMPAIRED DRIVING           1.010916
GRAND LARCENY OF MOTOR VEHICLE           0.889100
OTHER STATE LAWS                         0.802088
OFFENSES AGAINST THE PERSON              0.639139
NYS LAWS-UNCLASSIFIED FELONY             0.631229
MURDER & NON-NEGL. MANSLAUGHTE           0.598007
DISORDERLY CONDUCT                       0.498339
FRAUDS                                   0.409745
BURGLAR'S TOOLS                          0.286347
RAPE                                     0.278437
UNAUTHORIZED USE OF A VEHICLE            0.238886
CANNABIS RELATED OFFENSES                0.193007
OTHER STATE LAWS (NON PENAL LA           0.162949
PROSTITUTION & RELATED OFFENSES          0.148711
GAMBLING                                 0.112324
INTOXICATED/IMPAIRED DRIVING             0.107578
ALCOHOLIC BEVERAGE CONTROL LAW           0.088594
THEFT-FRAUD                              0.083847
OFFENSES AGAINST PUBLIC SAFETY           0.080683
ADMINISTRATIVE CODE                      0.077519
THEFT OF SERVICES                        0.066445
JOSTLING                                 0.055371
ARSON                                    0.052207
KIDNAPPING & RELATED OFFENSES            0.045879
ENDAN WELFARE INCOMP                     0.039551
HARRASSMENT 2                            0.033223
HOMICIDE-NEGLIGENT,UNCLASSIFIE           0.026894
AGRICULTURE & MRKTS LAW-UNCLASSIFIED     0.025312
CHILD ABANDONMENT/NON SUPPORT            0.018984
MOVING INFRACTIONS                       0.017402
FRAUDULENT ACCOSTING                     0.015820
DISRUPTION OF A RELIGIOUS SERV           0.009492
ESCAPE 3                                 0.004746
OTHER STATE LAWS (NON PENAL LAW)         0.004746
HOMICIDE-NEGLIGENT-VEHICLE               0.003164
ANTICIPATORY OFFENSES                    0.003164
KIDNAPPING                               0.003164
OFFENSES RELATED TO CHILDREN             0.003164
ADMINISTRATIVE CODES                     0.001582
FORTUNE TELLING                          0.001582
Name: OFNS_DESC, dtype: float64

#### Due to large number of unique values will be keepin as object type as opposed to categorical

In [177]:
df['ARREST_BORO'].unique()

array(['M', 'K', 'Q', 'B', 'S'], dtype=object)

In [178]:
df['ARREST_BORO'] = df['ARREST_BORO'].astype('category')

In [179]:
df['ARREST_PRECINCT'].unique()

array([ 26,  77, 106,  49,  81, 113,   6,  41, 102,  69,  79,  20,  47,
       114,  88,  17, 112,  14,  45,  32, 115,   1,  67, 120, 103,  23,
        63,  40, 108,  18,  46,  44,  60,  52, 110,   5, 105,  48, 121,
        83, 101,  43,  68, 104,  42,  72,  25,  71,  62,  73,  75,  84,
        24,  94,  66,  78,  33,  34,   7,  13,  30, 109, 107,  19,  70,
        90,  10,  50, 111,  28, 122,   9,  76,  61, 100, 123,  22])

In [180]:
df['ARREST_PRECINCT'] = df['ARREST_PRECINCT'].astype('category')

In [181]:
print(df['ARREST_BORO'].unique())

['M', 'K', 'Q', 'B', 'S']
Categories (5, object): ['B', 'K', 'M', 'Q', 'S']

In [182]:
#Originally brooklyn was under letter K as brooklyn is also known as Kings County

boro_mapping = {
    'M': 'Manhattan',
    'K': 'Brooklyn',
    'Q': 'Queens',
    'B': 'Bronx',
    'S': 'Staten Island'
}

# Rename categories using the dictionary
df['ARREST_BORO'] = df['ARREST_BORO'].cat.rename_categories(boro_mapping)

In [183]:
df['ARREST_BORO']

0            Manhattan
1             Brooklyn
2               Queens
3                Bronx
4             Brooklyn
             ...
63616         Brooklyn
63617        Manhattan
63618         Brooklyn
63619         Brooklyn
63620    Staten Island
Name: ARREST_BORO, Length: 63210, dtype: category
Categories (5, object): ['Bronx', 'Brooklyn', 'Manhattan', 'Queens', 'Staten Island']

In [184]:
df['PERP_SEX'].unique()

array(['M', 'F'], dtype=object)

In [185]:
sex_mapping = {
    'M': 'Male',
    'F': 'Female'
}

# Convert 'PERP_SEX' to categorical data type
df['PERP_SEX'] = df['PERP_SEX'].astype('category')

# Rename categories using the dictionary
df['PERP_SEX'] = df['PERP_SEX'].cat.rename_categories(sex_mapping)

In [186]:
df['PERP_RACE'].unique()

array(['BLACK', 'WHITE HISPANIC', 'WHITE', 'ASIAN / PACIFIC ISLANDER',
       'UNKNOWN', 'BLACK HISPANIC', 'AMERICAN INDIAN/ALASKAN NATIVE'],
      dtype=object)

In [187]:
df['PERP_RACE'] = df['PERP_RACE'].astype('category')

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63210 entries, 0 to 63620
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ARREST_KEY                63210 non-null  int64
 1   ARREST_DATE               63210 non-null  datetime64[ns]
 2   PD_CD                     63210 non-null  float64
 3   PD_DESC                   63210 non-null  object
 4   KY_CD                     63210 non-null  float64
 5   OFNS_DESC                 63210 non-null  object
 6   LAW_CODE                  63210 non-null  object
 7   LAW_CAT_CD                63210 non-null  object
 8   ARREST_BORO               63210 non-null  category
 9   ARREST_PRECINCT           63210 non-null  category
 10  JURISDICTION_CODE         63210 non-null  int64
 11  AGE_GROUP                 63210 non-null  object
 12  PERP_SEX                  63210 non-null  category
 13  PERP_RACE                 63210 non-null  category
 14  X_COORD_CD                63210 non-null  int64
 15  Y_COORD_CD                63210 non-null  int64
 16  Latitude                  63210 non-null  float64
 17  Longitude                 63210 non-null  float64
 18  New Georeferenced Column  63210 non-null  object
dtypes: category(4), datetime64[ns](1), float64(4), int64(4), object(6)
memory usage: 8.0+ MB

In [189]:
df['LAW_CAT_CD'].unique()

array(['F', 'M', 'V', '9', 'I'], dtype=object)

In [190]:
print(df.loc[df['LAW_CAT_CD'] == 'M']) #Misdomener

       ARREST_KEY ARREST_DATE  PD_CD                         PD_DESC  KY_CD  \
2       279895750  2024-01-03  101.0                       ASSAULT 3  344.0
3       280809090  2024-01-19  511.0  CONTROLLED SUBSTANCE, POSSESSI  235.0
6       280769124  2024-01-19  464.0                        JOSTLING  230.0
7       281338081  2024-01-30  101.0                       ASSAULT 3  344.0
15      281544391  2024-02-02  101.0                       ASSAULT 3  344.0
...           ...         ...    ...                             ...    ...
63613   283819808  2024-03-15  101.0                       ASSAULT 3  344.0
63616   282877412  2024-02-27  339.0  LARCENY,PETIT FROM OPEN AREAS,  341.0
63617   283628088  2024-03-12  511.0  CONTROLLED SUBSTANCE, POSSESSI  235.0
63619   283013910  2024-03-01  922.0  TRAFFIC,UNCLASSIFIED MISDEMEAN  348.0
63620   283495531  2024-03-10  203.0            TRESPASS 3, CRIMINAL  352.0

                          OFNS_DESC    LAW_CODE LAW_CAT_CD    ARREST_BORO  \
2      ASSAULT 3 & RELATED OFFENSES  PL 1200001          M         Queens
3                   DANGEROUS DRUGS  PL 2200300          M          Bronx
6                          JOSTLING  PL 1652501          M      Manhattan
7      ASSAULT 3 & RELATED OFFENSES  PL 1200001          M      Manhattan
15     ASSAULT 3 & RELATED OFFENSES  PL 1200001          M      Manhattan
...                             ...         ...        ...            ...
63613  ASSAULT 3 & RELATED OFFENSES  PL 1200001          M      Manhattan
63616                 PETIT LARCENY  PL 1552500          M       Brooklyn
63617               DANGEROUS DRUGS  PL 2200300          M      Manhattan
63619      VEHICLE AND TRAFFIC LAWS  VTL05110A4          M       Brooklyn
63620             CRIMINAL TRESPASS  PL 140100A          M  Staten Island

      ARREST_PRECINCT  JURISDICTION_CODE AGE_GROUP PERP_SEX  \
2                 106                  0       65+   Female
3                  49                  0     45-64     Male
6                   6                  0     25-44     Male
7                  26                  0     25-44     Male
15                 20                  0     45-64   Female
...               ...                ...       ...      ...
63613              13                  0     45-64     Male
63616              60                  0     45-64     Male
63617              13                  0     45-64     Male
63619              83                  0     25-44   Female
63620             123                  0     25-44     Male

                            PERP_RACE  X_COORD_CD  Y_COORD_CD   Latitude  \
2                               WHITE     1026836      180689  40.662526
3                               BLACK     1027430      251104  40.855793
6                               BLACK      984134      207984  40.737547
7                               BLACK      996014      236126  40.814780
15                              WHITE      991040      225092  40.784499
...                               ...         ...         ...        ...
63613  AMERICAN INDIAN/ALASKAN NATIVE      986930      207834  40.737133
63616                  WHITE HISPANIC      987154      149165  40.576100
63617                           BLACK      985689      208933  40.740151
63619                           BLACK     1007120      193913  40.698894
63620                           WHITE      930842      133050  40.531707

       Longitude                       New Georeferenced Column
2     -73.846499                   POINT (-73.846499 40.662526)
3     -73.843908                   POINT (-73.843908 40.855793)
6     -74.000415                   POINT (-74.000415 40.737547)
7     -73.957499                    POINT (-73.957499 40.81478)
15    -73.975480                    POINT (-73.97548 40.784499)
...          ...                                            ...
63613 -73.990329   POINT (-73.99032932220675 40.73713251623451)
63616 -73.989545                     POINT (-73.989545 40.5761)
63617 -73.994805                   POINT (-73.994805 40.740151)
63619 -73.917522  POINT (-73.91752179908735 40.698893568968515)
63620 -74.192126                   POINT (-74.192126 40.531707)

[35576 rows x 19 columns]

In [191]:
print(df.loc[df['LAW_CAT_CD'] == 'F']) #Felony

       ARREST_KEY ARREST_DATE  PD_CD                         PD_DESC  KY_CD  \
0       280255493  2024-01-10  397.0  ROBBERY,OPEN AREA UNCLASSIFIED  105.0
1       279805419  2024-01-02  157.0                          RAPE 1  104.0
4       280357135  2024-01-11  109.0        ASSAULT 2,1,UNCLASSIFIED  106.0
5       281488967  2024-02-01  157.0                          RAPE 1  104.0
9       281426006  2024-01-31  155.0                          RAPE 2  104.0
...           ...         ...    ...                             ...    ...
63610   283856690  2024-03-16  503.0  CONTROLLED SUBSTANCE,INTENT TO  117.0
63611   284520369  2024-03-29  503.0  CONTROLLED SUBSTANCE,INTENT TO  117.0
63614   284409873  2024-03-27  397.0  ROBBERY,OPEN AREA UNCLASSIFIED  105.0
63615   283436353  2024-03-08  729.0  FORGERY,ETC.,UNCLASSIFIED-FELO  113.0
63618   283387006  2024-03-07  397.0  ROBBERY,OPEN AREA UNCLASSIFIED  105.0

             OFNS_DESC    LAW_CODE LAW_CAT_CD ARREST_BORO ARREST_PRECINCT  \
0              ROBBERY  PL 1601001          F   Manhattan              26
1                 RAPE  PL 1303501          F    Brooklyn              77
4       FELONY ASSAULT  PL 1200502          F    Brooklyn              81
5                 RAPE  PL 1303501          F      Queens             113
9                 RAPE  PL 1303001          F       Bronx              41
...                ...         ...        ...         ...             ...
63610  DANGEROUS DRUGS  PL 2201601          F   Manhattan               9
63611  DANGEROUS DRUGS  PL 2201601          F   Manhattan              14
63614          ROBBERY  PL 1601001          F      Queens             113
63615          FORGERY  PL 1701501          F    Brooklyn              73
63618          ROBBERY  PL 160102A          F    Brooklyn              73

       JURISDICTION_CODE AGE_GROUP PERP_SEX                 PERP_RACE  \
0                      0       <18     Male                     BLACK
1                      0     25-44     Male            WHITE HISPANIC
4                      2     25-44   Female                     BLACK
5                      0     25-44     Male                     BLACK
9                      0     18-24     Male                     BLACK
...                  ...       ...      ...                       ...
63610                  1     25-44     Male                     BLACK
63611                  0     25-44     Male                     BLACK
63614                  3     45-64     Male  ASIAN / PACIFIC ISLANDER
63615                  0     18-24     Male                     BLACK
63618                  0     25-44     Male                     BLACK

       X_COORD_CD  Y_COORD_CD   Latitude  Longitude  \
0          996342      236149  40.814845 -73.956312
1         1003509      185018  40.674496 -73.930571
4         1002457      192292  40.694456 -73.934343
5         1046315      187088  40.679981 -73.776234
9         1013037      236657  40.816206 -73.896001
...           ...         ...        ...        ...
63610      989819      204094  40.726866 -73.979908
63611      986506      214124  40.754399 -73.991856
63614     1046315      187088  40.679981 -73.776234
63615     1011063      180396  40.661782 -73.903353
63618     1008227      183789  40.671104 -73.913562

                           New Georeferenced Column
0                      POINT (-73.956312 40.814845)
1        POINT (-73.9305713255961 40.6744956865259)
4                      POINT (-73.934343 40.694456)
5        POINT (-73.7762339071953 40.6799807384666)
9        POINT (-73.8960011932583 40.8162058439227)
...                                             ...
63610  POINT (-73.97990757169028 40.72686578692612)
63611                  POINT (-73.991856 40.754399)
63614    POINT (-73.7762339071953 40.6799807384666)
63615                  POINT (-73.903353 40.661782)
63618                  POINT (-73.913562 40.671104)

[26650 rows x 19 columns]

In [192]:
df.loc[df['LAW_CAT_CD'] == 'I'] #Traffic

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
1295,282058775,2024-02-12,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,LOC00000I0,I,Manhattan,30,1,25-44,Male,BLACK,996945,238532,40.821382,-73.954133,POINT (-73.95413257822179 40.821381691686916)
3632,280473444,2024-01-13,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL03750T2,I,Brooklyn,78,0,25-44,Male,BLACK,993703,182685,40.668101,-73.965923,POINT (-73.965923 40.668101)
4787,280063664,2024-01-06,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Brooklyn,90,0,45-64,Female,WHITE HISPANIC,998016,196598,40.706283,-73.950348,POINT (-73.950348 40.706283)
4911,279846195,2024-01-02,972.0,SEAT BELTS,880.0,MOVING INFRACTIONS,VTL1229C00,I,Brooklyn,90,0,25-44,Male,BLACK,999668,195748,40.703949,-73.944391,POINT (-73.944391 40.703949)
5165,280927162,2024-01-22,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0511A01,I,Queens,109,0,45-64,Male,WHITE HISPANIC,1032852,228739,40.794378,-73.824471,POINT (-73.82447061233147 40.79437808324494)
7896,281063433,2024-01-24,968.0,UNLICENSED OPERATOR,880.0,MOVING INFRACTIONS,VTL0509001,I,Brooklyn,68,0,25-44,Male,WHITE HISPANIC,979616,170814,40.635520,-74.016696,POINT (-74.01669615060825 40.63552029862381)
8919,280854796,2024-01-21,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL112800A,I,Queens,112,0,25-44,Female,WHITE HISPANIC,1029052,203660,40.725563,-73.838362,POINT (-73.83836166699767 40.725562860059284)
10356,281494723,2024-02-01,973.0,USE CELL PHONE WHILE DRIVING,880.0,MOVING INFRACTIONS,VTL1225C2A,I,Brooklyn,66,0,25-44,Male,WHITE,985588,169978,40.633227,-73.995179,POINT (-73.99517939541789 40.63322676726574)
11274,280209808,2024-01-09,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Manhattan,13,0,25-44,Male,BLACK HISPANIC,988971,207813,40.737074,-73.982962,POINT (-73.982962 40.737074)
11420,280041976,2024-01-05,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL040201A,I,Brooklyn,66,0,18-24,Male,WHITE HISPANIC,984900,171853,40.638373,-73.997658,POINT (-73.99765797112055 40.638373320496456)
12066,280079204,2024-01-06,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Manhattan,30,0,25-44,Male,WHITE HISPANIC,999750,241187,40.828666,-73.943989,POINT (-73.943989 40.828666)
14320,280357134,2024-01-11,899.0,"PARKR&R,UNCLASSIFIED VIOLATION",675.0,ADMINISTRATIVE CODE,PRL00000I0,I,Brooklyn,77,0,45-64,Male,BLACK,1002366,185299,40.675262,-73.934688,POINT (-73.934688 40.675262)
15155,280424870,2024-01-12,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,LOC00000I0,I,Manhattan,14,0,25-44,Male,BLACK,987078,215157,40.757232,-73.989792,POINT (-73.98979219054627 40.757232265258125)
15289,280172406,2024-01-09,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,LOC00000I0,I,Brooklyn,68,0,25-44,Male,BLACK HISPANIC,977714,172199,40.639321,-74.023550,POINT (-74.02355033576893 40.63932062885157)
15551,279981879,2024-01-04,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0381006,I,Manhattan,18,0,25-44,Male,WHITE HISPANIC,992091,216280,40.760312,-73.971696,POINT (-73.97169620386617 40.76031158830656)
18434,281061072,2024-01-24,972.0,SEAT BELTS,880.0,MOVING INFRACTIONS,VTL1229C03,I,Brooklyn,79,0,25-44,Male,BLACK,997183,187256,40.680642,-73.953371,POINT (-73.95337129343466 40.680641740225916)
19309,280357131,2024-01-11,899.0,"PARKR&R,UNCLASSIFIED VIOLATION",675.0,ADMINISTRATIVE CODE,PRL00000I0,I,Brooklyn,77,0,25-44,Male,BLACK,1002366,185299,40.675262,-73.934688,POINT (-73.934688 40.675262)
19714,282429299,2024-02-19,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL04020B2,I,Queens,106,11,25-44,Male,BLACK,1028198,181985,40.666074,-73.841584,POINT (-73.8415841743437 40.66607440229481)
22490,280145933,2024-01-08,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Manhattan,30,0,25-44,Male,WHITE HISPANIC,999750,241187,40.828666,-73.943989,POINT (-73.943989 40.828666)
23775,282427295,2024-02-18,968.0,UNLICENSED OPERATOR,880.0,MOVING INFRACTIONS,VTL0509001,I,Brooklyn,69,0,25-44,Male,BLACK,1015906,171092,40.636228,-73.885943,POINT (-73.88594322509347 40.63622799432001)
25523,282453610,2024-02-19,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL1192AI1,I,Brooklyn,79,0,25-44,Female,BLACK,996736,190196,40.688712,-73.954977,POINT (-73.95497746125987 40.68871200953901)
25774,282600150,2024-02-21,879.0,"ADM.CODE,UNCLASSIFIED VIOLATIO",675.0,ADMINISTRATIVE CODE,AC 0019190,I,Brooklyn,94,0,65+,Male,WHITE,1000676,203774,40.725974,-73.940737,POINT (-73.94073732572983 40.72597396687852)
26047,282359544,2024-02-16,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0319001,I,Brooklyn,90,0,25-44,Male,BLACK,997769,198569,40.711692,-73.951236,POINT (-73.95123582027239 40.71169241611257)
27382,282658439,2024-02-22,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL040101A,I,Bronx,44,0,25-44,Male,BLACK,1009388,242814,40.833110,-73.909156,POINT (-73.909156 40.83311)
28281,282232067,2024-02-14,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL1192AI1,I,Manhattan,34,0,65+,Male,WHITE,1002024,249023,40.850168,-73.935754,POINT (-73.93575420224671 40.85016768534703)
28853,281287945,2024-01-29,879.0,"ADM.CODE,UNCLASSIFIED VIOLATIO",675.0,ADMINISTRATIVE CODE,AC 0019190,I,Brooklyn,68,0,65+,Male,WHITE,983170,166508,40.623702,-74.003891,POINT (-74.00389051571055 40.62370238333524)
29305,282528396,2024-02-20,968.0,UNLICENSED OPERATOR,880.0,MOVING INFRACTIONS,VTL0509001,I,Bronx,40,0,18-24,Male,BLACK,1005737,232459,40.804696,-73.922386,POINT (-73.9223862687793 40.804695995292974)
30214,282232049,2024-02-14,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL03750T1,I,Brooklyn,63,0,18-24,Male,BLACK,1005769,161456,40.609810,-73.922498,POINT (-73.92249759633725 40.60980962699051)
31626,282808153,2024-02-26,939.0,IMPROPER LIGHTS,881.0,OTHER TRAFFIC INFRACTION,VTL03750XA,I,Queens,103,0,25-44,Male,BLACK,1039242,196467,40.705762,-73.801657,POINT (-73.80165667775871 40.70576236799419)
32190,283139344,2024-03-03,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL111000A,I,Brooklyn,63,0,45-64,Male,BLACK,1005769,161456,40.609810,-73.922498,POINT (-73.92249759633725 40.60980962699051)
37643,283321802,2024-03-06,968.0,UNLICENSED OPERATOR,880.0,MOVING INFRACTIONS,VTL0509001,I,Manhattan,13,0,18-24,Male,WHITE HISPANIC,985985,210395,40.744164,-73.993738,POINT (-73.993738 40.744164)
38392,282308042,2024-02-16,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0375002,I,Manhattan,34,0,25-44,Female,WHITE HISPANIC,1007190,253954,40.863690,-73.917064,POINT (-73.91706434332096 40.863689888315065)
38715,282030396,2024-02-11,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,LOC00000I0,I,Manhattan,14,1,45-64,Female,BLACK,987078,215157,40.757232,-73.989792,POINT (-73.98979219054627 40.757232265258125)
39876,282525541,2024-02-20,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL037502A,I,Queens,106,0,25-44,Male,ASIAN / PACIFIC ISLANDER,1034017,183955,40.671451,-73.820594,POINT (-73.820594 40.671451)
39926,281565780,2024-02-02,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL040101A,I,Brooklyn,67,0,25-44,Male,BLACK,1002624,171843,40.638327,-73.933793,POINT (-73.933793 40.638327)
40800,283103466,2024-03-02,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0319001,I,Manhattan,23,0,25-44,Male,BLACK,999389,228394,40.793552,-73.945325,POINT (-73.94532519621144 40.79355183824391)
41497,282350099,2024-02-16,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,LOC00000I0,I,Brooklyn,84,1,25-44,Male,BLACK,986894,189470,40.686728,-73.990466,POINT (-73.99046643880735 40.68672771840156)
41767,282771542,2024-02-25,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0402004,I,Brooklyn,79,0,25-44,Male,BLACK,1000801,186984,40.679889,-73.940328,POINT (-73.94032760874937 40.67988913658441)
41836,282805000,2024-02-26,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Brooklyn,70,0,25-44,Male,BLACK HISPANIC,991626,169071,40.630736,-73.973423,POINT (-73.973423 40.630736)
43105,283053888,2024-03-01,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,LOC00000I0,I,Bronx,45,0,65+,Female,BLACK,1027595,245901,40.841510,-73.843346,POINT (-73.8433457333335 40.841510223473726)
43466,282859886,2024-02-27,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0511A01,I,Queens,107,0,18-24,Female,ASIAN / PACIFIC ISLANDER,1037303,201084,40.718447,-73.808614,POINT (-73.80861379309259 40.71844674206585)
44810,281708542,2024-02-05,968.0,UNLICENSED OPERATOR,880.0,MOVING INFRACTIONS,VTL0509001,I,Manhattan,34,0,18-24,Male,BLACK HISPANIC,1007190,253954,40.863690,-73.917064,POINT (-73.91706434332096 40.863689888315065)
46857,284311706,2024-03-25,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0319001,I,Manhattan,28,0,45-64,Female,BLACK,998041,231228,40.801333,-73.950188,POINT (-73.95018770411934 40.80133260280658)
49413,283998772,2024-03-19,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL03750I0,I,Queens,103,0,25-44,Male,BLACK,1039070,195365,40.702739,-73.802286,POINT (-73.80228601065063 40.70273871215094)
50154,283255896,2024-03-05,972.0,SEAT BELTS,880.0,MOVING INFRACTIONS,VTL0383001,I,Queens,109,0,18-24,Male,WHITE HISPANIC,1030241,220836,40.772700,-73.833954,POINT (-73.8339544942983 40.77270046421115)
50930,284241203,2024-03-24,909.0,IMPAIRED DRIVING / ALCOHOL,880.0,MOVING INFRACTIONS,VTL119401B,I,Bronx,43,0,25-44,Male,WHITE HISPANIC,1019603,240960,40.827985,-73.872255,POINT (-73.872255 40.827985)
52930,284431312,2024-03-27,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Manhattan,18,0,45-64,Male,ASIAN / PACIFIC ISLANDER,988210,218129,40.765390,-73.985702,POINT (-73.985702 40.76539)
54056,282889512,2024-02-27,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL031901U,I,Bronx,41,0,25-44,Male,BLACK,1014216,238783,40.822031,-73.891729,POINT (-73.891729 40.822031)
59300,284311147,2024-03-25,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0319001,I,Brooklyn,90,0,25-44,Male,WHITE HISPANIC,1001724,195008,40.701911,-73.936979,POINT (-73.93697904524477 40.701911387269355)
59510,283820025,2024-03-15,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0511A01,I,Brooklyn,68,0,25-44,Female,BLACK,980155,170246,40.633962,-74.014754,POINT (-74.01475380657142 40.63396152491176)
61953,283581125,2024-03-12,940.0,LEAVING THE SCENE / PROPERTY DAMAGE / INJURED ...,881.0,OTHER TRAFFIC INFRACTION,VTL060001A,I,Bronx,43,0,45-64,Male,BLACK,1020183,239282,40.823378,-73.870168,POINT (-73.870168 40.823378)
61967,284194695,2024-03-22,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL0319001,I,Manhattan,25,0,25-44,Male,BLACK HISPANIC,1001167,229824,40.797475,-73.938898,POINT (-73.938898 40.797475)
62651,284433800,2024-03-27,969.0,"TRAFFIC,UNCLASSIFIED INFRACTIO",881.0,OTHER TRAFFIC INFRACTION,VTL03750A3,I,Staten Island,120,0,25-44,Female,WHITE HISPANIC,960775,165100,40.619807,-74.084560,POINT (-74.0845597593489 40.61980668312155)
63253,284215784,2024-03-23,968.0,UNLICENSED OPERATOR,880.0,MOVING INFRACTIONS,VTL0509001,I,Brooklyn,68,0,25-44,Male,BLACK HISPANIC,979644,163943,40.616662,-74.016590,POINT (-74.01659 40.616662)

In [193]:
df.loc[df['LAW_CAT_CD'] == '9']

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
126,280561265,2024-01-15,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3,25-44,Male,WHITE,1046315,187088,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
261,280775790,2024-01-19,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3,45-64,Male,WHITE,1046315,187088,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
497,280690858,2024-01-17,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3,25-44,Female,ASIAN / PACIFIC ISLANDER,1046315,187088,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
1017,281103899,2024-01-25,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,102,0,25-44,Female,BLACK,1032501,198800,40.712206,-73.825952,POINT (-73.825952 40.712206)
2027,279954060,2024-01-04,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3,18-24,Male,BLACK,1046315,187088,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61454,283343080,2024-03-07,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,114,0,25-44,Male,BLACK,1016256,226893,40.789387,-73.884416,POINT (-73.884416 40.789387)
62599,284433795,2024-03-27,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3,25-44,Male,WHITE HISPANIC,1046315,187088,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
62976,283624674,2024-03-12,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,113,3,25-44,Male,BLACK,1046315,187088,40.679981,-73.776234,POINT (-73.7762339071953 40.6799807384666)
63177,284323723,2024-03-26,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,107,0,45-64,Male,BLACK,1036628,204948,40.729059,-73.811018,POINT (-73.811018 40.729059)
63312,284137207,2024-03-21,849.0,"NY STATE LAWS,UNCLASSIFIED VIO",677.0,OTHER STATE LAWS,CPL5700600,9,Queens,102,0,45-64,Male,WHITE,1032501,198800,40.712206,-73.825952,POINT (-73.825952 40.712206)

In [194]:
law_cat = {
    'F': 'Felony',
    'M': 'Misdemeanor',
    'V': 'Violation',
    '9': 'Unclassified Violation',
    'I': 'Traffic'
}

# Convert 'PERP_SEX' to categorical data type
df['LAW_CAT_CD'] = df['LAW_CAT_CD'].astype('category')

# Rename categories using the dictionary
df['LAW_CAT_CD'] = df['LAW_CAT_CD'].cat.rename_categories(law_cat)

In [195]:
df['JURISDICTION_CODE'].unique()

array([ 0,  2, 17,  1,  3, 97, 73, 72, 71, 87, 51, 11,  7, 14, 12, 52, 79,
        4, 88, 13, 69, 85, 16, 76, 74])

In [196]:
df['JURISDICTION_CODE'] = df['JURISDICTION_CODE'].astype('category')

In [197]:
df

,ARREST_KEY,ARREST_DATE,PD_CD,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,X_COORD_CD,Y_COORD_CD,Latitude,Longitude,New Georeferenced Column
0,280255493,2024-01-10,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,Felony,Manhattan,26,0,<18,Male,BLACK,996342,236149,40.814845,-73.956312,POINT (-73.956312 40.814845)
1,279805419,2024-01-02,157.0,RAPE 1,104.0,RAPE,PL 1303501,Felony,Brooklyn,77,0,25-44,Male,WHITE HISPANIC,1003509,185018,40.674496,-73.930571,POINT (-73.9305713255961 40.6744956865259)
2,279895750,2024-01-03,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,Misdemeanor,Queens,106,0,65+,Female,WHITE,1026836,180689,40.662526,-73.846499,POINT (-73.846499 40.662526)
3,280809090,2024-01-19,511.0,"CONTROLLED SUBSTANCE, POSSESSI",235.0,DANGEROUS DRUGS,PL 2200300,Misdemeanor,Bronx,49,0,45-64,Male,BLACK,1027430,251104,40.855793,-73.843908,POINT (-73.843908 40.855793)
4,280357135,2024-01-11,109.0,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,Felony,Brooklyn,81,2,25-44,Female,BLACK,1002457,192292,40.694456,-73.934343,POINT (-73.934343 40.694456)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63616,282877412,2024-02-27,339.0,"LARCENY,PETIT FROM OPEN AREAS,",341.0,PETIT LARCENY,PL 1552500,Misdemeanor,Brooklyn,60,0,45-64,Male,WHITE HISPANIC,987154,149165,40.576100,-73.989545,POINT (-73.989545 40.5761)
63617,283628088,2024-03-12,511.0,"CONTROLLED SUBSTANCE, POSSESSI",235.0,DANGEROUS DRUGS,PL 2200300,Misdemeanor,Manhattan,13,0,45-64,Male,BLACK,985689,208933,40.740151,-73.994805,POINT (-73.994805 40.740151)
63618,283387006,2024-03-07,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 160102A,Felony,Brooklyn,73,0,25-44,Male,BLACK,1008227,183789,40.671104,-73.913562,POINT (-73.913562 40.671104)
63619,283013910,2024-03-01,922.0,"TRAFFIC,UNCLASSIFIED MISDEMEAN",348.0,VEHICLE AND TRAFFIC LAWS,VTL05110A4,Misdemeanor,Brooklyn,83,0,25-44,Female,BLACK,1007120,193913,40.698894,-73.917522,POINT (-73.91752179908735 40.698893568968515)
63620,283495531,2024-03-10,203.0,"TRESPASS 3, CRIMINAL",352.0,CRIMINAL TRESPASS,PL 140100A,Misdemeanor,Staten Island,123,0,25-44,Male,WHITE,930842,133050,40.531707,-74.192126,POINT (-74.192126 40.531707)

In [198]:
df['AGE_GROUP'] = df['AGE_GROUP'].astype('category')

In [199]:
df['OFNS_DESC'].unique()

array(['ROBBERY', 'RAPE', 'ASSAULT 3 & RELATED OFFENSES',
       'DANGEROUS DRUGS', 'FELONY ASSAULT', 'JOSTLING', 'ARSON',
       'BURGLARY', 'DANGEROUS WEAPONS', 'MISCELLANEOUS PENAL LAW',
       'VEHICLE AND TRAFFIC LAWS', 'PETIT LARCENY', 'CRIMINAL TRESPASS',
       'GRAND LARCENY', 'OTHER OFFENSES RELATED TO THEF',
       'GRAND LARCENY OF MOTOR VEHICLE', 'CRIMINAL MISCHIEF & RELATED OF',
       'OFF. AGNST PUB ORD SENSBLTY &', 'OTHER TRAFFIC INFRACTION',
       'OFFENSES AGAINST PUBLIC ADMINI', 'DISORDERLY CONDUCT',
       'SEX CRIMES', 'FORGERY', 'NYS LAWS-UNCLASSIFIED FELONY',
       'POSSESSION OF STOLEN PROPERTY', 'OTHER STATE LAWS',
       'MURDER & NON-NEGL. MANSLAUGHTE', 'INTOXICATED & IMPAIRED DRIVING',
       'OFFENSES INVOLVING FRAUD', 'CANNABIS RELATED OFFENSES',
       'OFFENSES AGAINST THE PERSON', 'FRAUDS',
       'ALCOHOLIC BEVERAGE CONTROL LAW', 'OTHER STATE LAWS (NON PENAL LA',
       'ENDAN WELFARE INCOMP', 'UNAUTHORIZED USE OF A VEHICLE',
       'ADMINISTRATIVE CODE', 'GAMBLING',
       'PROSTITUTION & RELATED OFFENSES', "BURGLAR'S TOOLS",
       'INTOXICATED/IMPAIRED DRIVING',
       'AGRICULTURE & MRKTS LAW-UNCLASSIFIED', 'THEFT OF SERVICES',
       'OFFENSES AGAINST PUBLIC SAFETY', 'THEFT-FRAUD',
       'KIDNAPPING & RELATED OFFENSES', 'HARRASSMENT 2',
       'MOVING INFRACTIONS', 'FRAUDULENT ACCOSTING', 'ESCAPE 3',
       'ANTICIPATORY OFFENSES', 'KIDNAPPING',
       'HOMICIDE-NEGLIGENT,UNCLASSIFIE', 'CHILD ABANDONMENT/NON SUPPORT',
       'OTHER STATE LAWS (NON PENAL LAW)', 'ADMINISTRATIVE CODES',
       'HOMICIDE-NEGLIGENT-VEHICLE', 'DISRUPTION OF A RELIGIOUS SERV',
       'FORTUNE TELLING', 'OFFENSES RELATED TO CHILDREN'], dtype=object)

In [200]:
#Changing to categorical for model usage down the line
df['OFNS_DESC'] = df['OFNS_DESC'].astype('category')

In [201]:
unique_law_codes = df['LAW_CODE'].unique()
total_unique_law_codes = len(unique_law_codes)
print(f"Total unique law codes: {total_unique_law_codes}")
df['LAW_CODE'] = df['LAW_CODE'].astype('category')

Total unique law codes: 758

In [202]:
df['PD_DESC'].unique()
unique_pd_desc = df['PD_DESC'].unique()
total_unique_pd_desc = len(unique_pd_desc)
print(f"Total unique pd descriptions: {total_unique_pd_desc }")
df['PD_DESC'] = df['PD_DESC'].astype('category')

Total unique pd descriptions: 213

In [203]:
df.drop(columns=['ARREST_KEY','X_COORD_CD', 'Y_COORD_CD','ARREST_KEY','New Georeferenced Column','PD_CD'] ,axis=1, inplace=True)

In [204]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 63210 entries, 0 to 63620
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   ARREST_DATE        63210 non-null  datetime64[ns]
 1   PD_DESC            63210 non-null  category
 2   KY_CD              63210 non-null  float64
 3   OFNS_DESC          63210 non-null  category
 4   LAW_CODE           63210 non-null  category
 5   LAW_CAT_CD         63210 non-null  category
 6   ARREST_BORO        63210 non-null  category
 7   ARREST_PRECINCT    63210 non-null  category
 8   JURISDICTION_CODE  63210 non-null  category
 9   AGE_GROUP          63210 non-null  category
 10  PERP_SEX           63210 non-null  category
 11  PERP_RACE          63210 non-null  category
 12  Latitude           63210 non-null  float64
 13  Longitude          63210 non-null  float64
dtypes: category(10), datetime64[ns](1), float64(3)
memory usage: 3.2 MB

In [205]:
df.head()

,ARREST_DATE,PD_DESC,KY_CD,OFNS_DESC,LAW_CODE,LAW_CAT_CD,ARREST_BORO,ARREST_PRECINCT,JURISDICTION_CODE,AGE_GROUP,PERP_SEX,PERP_RACE,Latitude,Longitude
0,2024-01-10,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,PL 1601001,Felony,Manhattan,26,0,<18,Male,BLACK,40.814845,-73.956312
1,2024-01-02,RAPE 1,104.0,RAPE,PL 1303501,Felony,Brooklyn,77,0,25-44,Male,WHITE HISPANIC,40.674496,-73.930571
2,2024-01-03,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,PL 1200001,Misdemeanor,Queens,106,0,65+,Female,WHITE,40.662526,-73.846499
3,2024-01-19,"CONTROLLED SUBSTANCE, POSSESSI",235.0,DANGEROUS DRUGS,PL 2200300,Misdemeanor,Bronx,49,0,45-64,Male,BLACK,40.855793,-73.843908
4,2024-01-11,"ASSAULT 2,1,UNCLASSIFIED",106.0,FELONY ASSAULT,PL 1200502,Felony,Brooklyn,81,2,25-44,Female,BLACK,40.694456,-73.934343

## I changed all object data types from Obj to category for both memory and ability to attempt to use modeling techniques down the line. for future refrence may just run a for loop from code below

for column in df.columns:
    if df[column].dtype == 'object':
        df[column] = df[column].astype('category')

In [206]:
df.to_csv('cleaned_nypd_arrest_date.csv',index= False)